name = "snice"
compatibility_date = "2025-01-01"
main = "src/worker.ts"

routes = [
  { pattern = "snice.dev", custom_domain = true },
  { pattern = "www.snice.dev", custom_domain = true }
]

[assets]
directory = "dist/site"
binding = "ASSETS"
run_worker_first = true
