import type { Meta, StoryObj } from '@storybook/html-vite';
import './snice-avatar';
import type { AvatarSize, AvatarShape } from './snice-avatar.types';

type Args = {
  src?: string;
  alt?: string;
  name?: string;
  size?: AvatarSize;
  shape?: AvatarShape;
  fallbackColor?: string;
  fallbackBackground?: string;
};

const SIZES: AvatarSize[] = ['xs', 'small', 'medium', 'large', 'xl', 'xxl'];
const SHAPES: AvatarShape[] = ['circle', 'square', 'rounded'];

function makeAvatar(attrs: Record<string, string> = {}): HTMLElement {
  const el = document.createElement('snice-avatar');
  for (const [k, v] of Object.entries(attrs)) {
    el.setAttribute(k, v);
  }
  return el;
}

function row(...els: HTMLElement[]): HTMLElement {
  const wrap = document.createElement('div');
  wrap.style.cssText = 'display:flex;align-items:center;gap:.75rem;flex-wrap:wrap;';
  els.forEach(el => wrap.appendChild(el));
  return wrap;
}

const meta: Meta<Args> = {
  title: 'Data/Avatar',
  component: 'snice-avatar',
  tags: ['autodocs'],
  argTypes: {
    src:                { control: 'text' },
    alt:                { control: 'text' },
    name:               { control: 'text' },
    size:               { control: 'select', options: SIZES },
    shape:              { control: 'select', options: SHAPES },
    fallbackColor:      { control: 'color' },
    fallbackBackground: { control: 'color' },
  },
  render: (args) => {
    const el = document.createElement('snice-avatar');
    if (args.src               !== undefined) el.setAttribute('src',                 args.src);
    if (args.alt               !== undefined) el.setAttribute('alt',                 args.alt);
    if (args.name              !== undefined) el.setAttribute('name',                args.name);
    if (args.size              !== undefined) el.setAttribute('size',                args.size);
    if (args.shape             !== undefined) el.setAttribute('shape',               args.shape);
    if (args.fallbackColor     !== undefined) el.setAttribute('fallback-color',      args.fallbackColor);
    if (args.fallbackBackground !== undefined) el.setAttribute('fallback-background', args.fallbackBackground);
    return el;
  },
};
export default meta;

type Story = StoryObj<Args>;

export const Default: Story = { args: { name: 'Ada Lovelace', size: 'medium', shape: 'circle' } };

// h2: All Sizes — Initials
export const AllSizesInitials: Story = {
  render: () => row(...SIZES.map(size => makeAvatar({ size, name: 'Ada Lovelace' }))),
};

// h2: All Sizes — Image
export const AllSizesImage: Story = {
  render: () => row(...SIZES.map(size => makeAvatar({ size, src: 'https://i.pravatar.cc/200?img=1', name: 'User' }))),
};

// h2: All Sizes — No Name (Default Icon)
export const AllSizesNoName: Story = {
  render: () => row(...SIZES.map(size => makeAvatar({ size }))),
};

// h2: Shape × Size Matrix
export const ShapeXSizeMatrix: Story = {
  render: () => {
    const grid = document.createElement('div');
    grid.style.cssText = 'display:grid;grid-template-columns:auto repeat(6,1fr);gap:.75rem;align-items:center;';
    for (const shape of SHAPES) {
      const lbl = document.createElement('div');
      lbl.style.cssText = 'font-size:.7rem;color:#888;text-align:right;padding-right:.5rem;';
      lbl.textContent = shape;
      grid.appendChild(lbl);
      for (const size of SIZES) {
        grid.appendChild(makeAvatar({ shape, size, name: 'AL' }));
      }
    }
    return grid;
  },
};

// h2: Shape × Image
export const ShapeXImage: Story = {
  render: () => row(
    makeAvatar({ shape: 'circle',  size: 'xl', src: 'https://i.pravatar.cc/200?img=3', name: 'User' }),
    makeAvatar({ shape: 'square',  size: 'xl', src: 'https://i.pravatar.cc/200?img=3', name: 'User' }),
    makeAvatar({ shape: 'rounded', size: 'xl', src: 'https://i.pravatar.cc/200?img=3', name: 'User' }),
  ),
};

// h2: Image Fallback — Broken URL
export const ImageFallbackBrokenUrl: Story = {
  render: () => row(
    makeAvatar({ src: 'https://broken.invalid/404.jpg', name: 'Fallback Test' }),
    makeAvatar({ src: 'https://broken.invalid/404.jpg', name: 'No Image' }),
    makeAvatar({ src: 'https://broken.invalid/404.jpg' }),
  ),
};

// h2: Auto-Generated Colors — 20 Names
export const AutoGeneratedColors20Names: Story = {
  render: () => {
    const names = ['Alice', 'Bob', 'Carol', 'David', 'Eve', 'Frank', 'Grace', 'Henry',
                   'Iris', 'Jack', 'Karen', 'Leo', 'Mia', 'Nina', 'Oscar', 'Pia',
                   'Quinn', 'Ray', 'Sara', 'Tom'];
    const grid = document.createElement('div');
    grid.style.cssText = 'display:grid;grid-template-columns:repeat(auto-fill,minmax(3.5rem,1fr));gap:.75rem;';
    for (const name of names) {
      const item = document.createElement('div');
      item.style.cssText = 'display:flex;flex-direction:column;align-items:center;gap:.35rem;';
      item.appendChild(makeAvatar({ name }));
      const span = document.createElement('span');
      span.style.cssText = 'font-size:.6rem;color:#888;';
      span.textContent = name;
      item.appendChild(span);
      grid.appendChild(item);
    }
    return grid;
  },
};

// h2: Custom Fallback Colors
export const CustomFallbackColors: Story = {
  render: () => row(
    makeAvatar({ name: 'Red',    'fallback-background': '#dc2626', 'fallback-color': '#fff', size: 'large' }),
    makeAvatar({ name: 'Blue',   'fallback-background': '#2563eb', 'fallback-color': '#fff', size: 'large' }),
    makeAvatar({ name: 'Green',  'fallback-background': '#16a34a', 'fallback-color': '#fff', size: 'large' }),
    makeAvatar({ name: 'Purple', 'fallback-background': '#7c3aed', 'fallback-color': '#fff', size: 'large' }),
    makeAvatar({ name: 'Pink',   'fallback-background': '#db2777', 'fallback-color': '#fff', size: 'large' }),
    makeAvatar({ name: 'Amber',  'fallback-background': '#d97706', 'fallback-color': '#fff', size: 'large' }),
    makeAvatar({ name: 'Teal',   'fallback-background': '#0d9488', 'fallback-color': '#fff', size: 'large' }),
    makeAvatar({ name: 'Dark',   'fallback-background': '#1e293b', 'fallback-color': '#94a3b8', size: 'large' }),
  ),
};

// h2: Initials Extraction
export const InitialsExtraction: Story = {
  render: () => {
    const grid = document.createElement('div');
    grid.style.cssText = 'display:grid;grid-template-columns:repeat(auto-fill,minmax(5rem,1fr));gap:1rem;';
    const cases: [string, string][] = [
      ['A', 'A'],
      ['AB', 'AB'],
      ['Ada Lovelace', 'Ada Lovelace'],
      ['Jean-Paul Sartre', 'Jean-Paul Sartre'],
      ['Mary Jane Watson-Parker', 'M.J. Watson-Parker'],
      ['中文名', '中文名'],
    ];
    for (const [name, label] of cases) {
      const item = document.createElement('div');
      item.style.cssText = 'display:flex;flex-direction:column;align-items:center;gap:.35rem;';
      item.appendChild(makeAvatar({ name }));
      const span = document.createElement('span');
      span.style.cssText = 'font-size:.65rem;color:#888;text-align:center;';
      span.textContent = label;
      item.appendChild(span);
      grid.appendChild(item);
    }
    return grid;
  },
};

// h2: Mixed Content Row
export const MixedContentRow: Story = {
  render: () => row(
    makeAvatar({ src: 'https://i.pravatar.cc/200?img=5', name: 'Image', size: 'large' }),
    makeAvatar({ name: 'Initials', size: 'large' }),
    makeAvatar({ size: 'large' }),
    makeAvatar({ src: 'https://broken.invalid/x.jpg', name: 'Broken', size: 'large' }),
    makeAvatar({ name: 'Custom', 'fallback-background': '#7c3aed', 'fallback-color': '#fff', size: 'large' }),
    makeAvatar({ name: 'Square', shape: 'square', size: 'large' }),
    makeAvatar({ name: 'Rounded', shape: 'rounded', size: 'large' }),
  ),
};
