/**
 * React adapter tests for Accordion
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Accordion: any;

try {
  const module = await import('../../../adapters/react/accordion');
  Accordion = module.Accordion;
} catch (error) {
  console.warn('React adapter for accordion not built yet. Run: npm run build:react');
  Accordion = null;
}

describe('React Adapter: Accordion', () => {
  if (!Accordion) {
    it.skip('Accordion adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Accordion',
    Component: Accordion,
    defaultProps: {}
  });
});
