/**
 * React adapter tests for ActionBar
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let ActionBar: any;

try {
  const module = await import('../../../adapters/react/action-bar');
  ActionBar = module.ActionBar;
} catch (error) {
  console.warn('React adapter for action-bar not built yet. Run: npm run build:react');
  ActionBar = null;
}

describe('React Adapter: ActionBar', () => {
  if (!ActionBar) {
    it.skip('ActionBar adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'ActionBar',
    Component: ActionBar,
    properties: [
      { name: 'open', value: 'test' },
      { name: 'position', value: 'top' },
      { name: 'noAnimation', value: 'test' },
      { name: 'noEscapeDismiss', value: 'test' }
    ],
    events: [
      { name: 'onActionBarOpen' },
      { name: 'onActionBarClose' }
    ],
    variants: ["default","pill"],
    sizes: ["small","medium"],
    defaultProps: {}
  });
});
