/**
 * React adapter tests for ActivityFeed
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let ActivityFeed: any;

try {
  const module = await import('../../../adapters/react/activity-feed');
  ActivityFeed = module.ActivityFeed;
} catch (error) {
  console.warn('React adapter for activity-feed not built yet. Run: npm run build:react');
  ActivityFeed = null;
}

describe('React Adapter: ActivityFeed', () => {
  if (!ActivityFeed) {
    it.skip('ActivityFeed adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'ActivityFeed',
    Component: ActivityFeed,
    defaultProps: {}
  });
});
