/**
 * React adapter tests for Alert
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Alert: any;

try {
  const module = await import('../../../adapters/react/alert');
  Alert = module.Alert;
} catch (error) {
  console.warn('React adapter for alert not built yet. Run: npm run build:react');
  Alert = null;
}

describe('React Adapter: Alert', () => {
  if (!Alert) {
    it.skip('Alert adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Alert',
    Component: Alert,
    properties: [
      { name: 'dismissible', value: 'test' },
      { name: 'icon', value: 'test' }
    ],
    events: [
      { name: 'onDismiss' }
    ],
    variants: ["info","success","warning","error"],
    sizes: ["small","medium","large"],
    defaultProps: {}
  });
});
