/**
 * React adapter tests for AppTiles
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let AppTiles: any;

try {
  const module = await import('../../../adapters/react/app-tiles');
  AppTiles = module.AppTiles;
} catch (error) {
  console.warn('React adapter for app-tiles not built yet. Run: npm run build:react');
  AppTiles = null;
}

describe('React Adapter: AppTiles', () => {
  if (!AppTiles) {
    it.skip('AppTiles adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'AppTiles',
    Component: AppTiles,
    defaultProps: {}
  });
});
