/**
 * React adapter tests for ApprovalFlow
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let ApprovalFlow: any;

try {
  const module = await import('../../../adapters/react/approval-flow');
  ApprovalFlow = module.ApprovalFlow;
} catch (error) {
  console.warn('React adapter for approval-flow not built yet. Run: npm run build:react');
  ApprovalFlow = null;
}

describe('React Adapter: ApprovalFlow', () => {
  if (!ApprovalFlow) {
    it.skip('ApprovalFlow adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'ApprovalFlow',
    Component: ApprovalFlow,
    defaultProps: {}
  });
});
