/**
 * React adapter tests for AudioRecorder
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let AudioRecorder: any;

try {
  const module = await import('../../../adapters/react/audio-recorder');
  AudioRecorder = module.AudioRecorder;
} catch (error) {
  console.warn('React adapter for audio-recorder not built yet. Run: npm run build:react');
  AudioRecorder = null;
}

describe('React Adapter: AudioRecorder', () => {
  if (!AudioRecorder) {
    it.skip('AudioRecorder adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'AudioRecorder',
    Component: AudioRecorder,
    defaultProps: {}
  });
});
