/**
 * React adapter tests for Availability
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Availability: any;

try {
  const module = await import('../../../adapters/react/availability');
  Availability = module.Availability;
} catch (error) {
  console.warn('React adapter for availability not built yet. Run: npm run build:react');
  Availability = null;
}

describe('React Adapter: Availability', () => {
  if (!Availability) {
    it.skip('Availability adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Availability',
    Component: Availability,
    defaultProps: {}
  });
});
