/**
 * React adapter tests for AvatarGroup
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let AvatarGroup: any;

try {
  const module = await import('../../../adapters/react/avatar-group');
  AvatarGroup = module.AvatarGroup;
} catch (error) {
  console.warn('React adapter for avatar-group not built yet. Run: npm run build:react');
  AvatarGroup = null;
}

describe('React Adapter: AvatarGroup', () => {
  if (!AvatarGroup) {
    it.skip('AvatarGroup adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'AvatarGroup',
    Component: AvatarGroup,
    defaultProps: {}
  });
});
