/**
 * React adapter tests for Avatar
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Avatar: any;

try {
  const module = await import('../../../adapters/react/avatar');
  Avatar = module.Avatar;
} catch (error) {
  console.warn('React adapter for avatar not built yet. Run: npm run build:react');
  Avatar = null;
}

describe('React Adapter: Avatar', () => {
  if (!Avatar) {
    it.skip('Avatar adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Avatar',
    Component: Avatar,
    defaultProps: {}
  });
});
