/**
 * React adapter tests for Badge
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Badge: any;

try {
  const module = await import('../../../adapters/react/badge');
  Badge = module.Badge;
} catch (error) {
  console.warn('React adapter for badge not built yet. Run: npm run build:react');
  Badge = null;
}

describe('React Adapter: Badge', () => {
  if (!Badge) {
    it.skip('Badge adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Badge',
    Component: Badge,
    properties: [
      { name: 'content', value: 'test' },
      { name: 'max', value: 10 },
      { name: 'dot', value: 'test' }
    ],
    variants: ["default","primary","secondary","success","warning","error"],
    sizes: ["small","medium","large"],
    defaultProps: {}
  });
});
