/**
 * React adapter tests for Banner
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Banner: any;

try {
  const module = await import('../../../adapters/react/banner');
  Banner = module.Banner;
} catch (error) {
  console.warn('React adapter for banner not built yet. Run: npm run build:react');
  Banner = null;
}

describe('React Adapter: Banner', () => {
  if (!Banner) {
    it.skip('Banner adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Banner',
    Component: Banner,
    defaultProps: {}
  });
});
