/**
 * React adapter tests for Binpack
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Binpack: any;

try {
  const module = await import('../../../adapters/react/binpack');
  Binpack = module.Binpack;
} catch (error) {
  console.warn('React adapter for binpack not built yet. Run: npm run build:react');
  Binpack = null;
}

describe('React Adapter: Binpack', () => {
  if (!Binpack) {
    it.skip('Binpack adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Binpack',
    Component: Binpack,
    properties: [
      { name: 'gap', value: 'test' },
      { name: 'columnWidth', value: 'test' },
      { name: 'rowHeight', value: 'test' },
      { name: 'horizontal', value: 'test' },
      { name: 'originLeft', value: 'test' },
      { name: 'originTop', value: 'test' },
      { name: 'transitionDuration', value: 'test' },
      { name: 'stagger', value: 'test' },
      { name: 'resize', value: 'vertical' }
    ],
    events: [
      { name: 'onBinpackLayoutComplete' },
      { name: 'onBinpackFitComplete' }
    ],
    defaultProps: {}
  });
});
