/**
 * React adapter tests for Book
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Book: any;

try {
  const module = await import('../../../adapters/react/book');
  Book = module.Book;
} catch (error) {
  console.warn('React adapter for book not built yet. Run: npm run build:react');
  Book = null;
}

describe('React Adapter: Book', () => {
  if (!Book) {
    it.skip('Book adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Book',
    Component: Book,
    properties: [
      { name: 'currentPage', value: 'test' },
      { name: 'mode', value: 'test' },
      { name: 'coverImage', value: 'test' },
      { name: 'title', value: 'test' },
      { name: 'author', value: 'test' }
    ],
    events: [
      { name: 'onPageTurn' },
      { name: 'onPageFlipStart' },
      { name: 'onPageFlipEnd' }
    ],
    defaultProps: {}
  });
});
