/**
 * React adapter tests for Booking
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Booking: any;

try {
  const module = await import('../../../adapters/react/booking');
  Booking = module.Booking;
} catch (error) {
  console.warn('React adapter for booking not built yet. Run: npm run build:react');
  Booking = null;
}

describe('React Adapter: Booking', () => {
  if (!Booking) {
    it.skip('Booking adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Booking',
    Component: Booking,
    defaultProps: {}
  });
});
