/**
 * React adapter tests for Booking
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Booking: any;

try {
  const module = await import('../../../adapters/react/booking');
  Booking = module.Booking;
} catch (error) {
  console.warn('React adapter for booking not built yet. Run: npm run build:react');
  Booking = null;
}

describe('React Adapter: Booking', () => {
  if (!Booking) {
    it.skip('Booking adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Booking',
    Component: Booking,
    properties: [
      { name: 'availableDates', value: ['2024-01-15', '2024-01-16', '2024-01-17'] },
      { name: 'availableSlots', value: ['09:00', '10:00', '11:00'] },
      { name: 'duration', value: 60 },
      { name: 'minDate', value: '2024-01-01' },
      { name: 'maxDate', value: '2024-12-31' },
      { name: 'fields', value: [{ name: 'name', required: true }] },
      { name: 'variant', value: 'default' }
    ],
    events: [],
    variants: ['default', 'compact', 'minimal'],
    defaultProps: {}
  });
});
