/**
 * React adapter tests for Breadcrumbs
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Breadcrumbs: any;

try {
  const module = await import('../../../adapters/react/breadcrumbs');
  Breadcrumbs = module.Breadcrumbs;
} catch (error) {
  console.warn('React adapter for breadcrumbs not built yet. Run: npm run build:react');
  Breadcrumbs = null;
}

describe('React Adapter: Breadcrumbs', () => {
  if (!Breadcrumbs) {
    it.skip('Breadcrumbs adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Breadcrumbs',
    Component: Breadcrumbs,
    defaultProps: {}
  });
});
