/**
 * React adapter tests for Button
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Button: any;

try {
  const module = await import('../../../adapters/react/button');
  Button = module.Button;
} catch (error) {
  console.warn('React adapter for button not built yet. Run: npm run build:react');
  Button = null;
}

describe('React Adapter: Button', () => {
  if (!Button) {
    it.skip('Button adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Button',
    Component: Button,
    properties: [
      { name: 'disabled', value: true },
      { name: 'loading', value: true }
    ],
    events: [
      { name: 'onClick' }
    ],
    variants: ["default","primary","secondary","danger","text","outline"],
    sizes: ["small","medium","large"],
    defaultProps: {}
  });
});
