/**
 * React adapter tests for Calendar
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Calendar: any;

try {
  const module = await import('../../../adapters/react/calendar');
  Calendar = module.Calendar;
} catch (error) {
  console.warn('React adapter for calendar not built yet. Run: npm run build:react');
  Calendar = null;
}

describe('React Adapter: Calendar', () => {
  if (!Calendar) {
    it.skip('Calendar adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Calendar',
    Component: Calendar,
    defaultProps: {}
  });
});
