/**
 * React adapter tests for Camera
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Camera: any;

try {
  const module = await import('../../../adapters/react/camera');
  Camera = module.Camera;
} catch (error) {
  console.warn('React adapter for camera not built yet. Run: npm run build:react');
  Camera = null;
}

describe('React Adapter: Camera', () => {
  if (!Camera) {
    it.skip('Camera adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Camera',
    Component: Camera,
    defaultProps: {}
  });
});
