/**
 * React adapter tests for CameraAnnotate
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let CameraAnnotate: any;

try {
  const module = await import('../../../adapters/react/camera-annotate');
  CameraAnnotate = module.CameraAnnotate;
} catch (error) {
  console.warn('React adapter for camera-annotate not built yet. Run: npm run build:react');
  CameraAnnotate = null;
}

describe('React Adapter: CameraAnnotate', () => {
  if (!CameraAnnotate) {
    it.skip('CameraAnnotate adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'CameraAnnotate',
    Component: CameraAnnotate,
    properties: [
      { name: 'mode', value: 'test' },
      { name: 'autoRotateColors', value: 'test' },
      { name: 'showLabelsPanel', value: 'test' }
    ],
    events: [
      { name: 'onCapture' },
      { name: 'onAnnotate' },
      { name: 'onAnnotationChange' }
    ],
    defaultProps: {}
  });
});
