/**
 * React adapter tests for Candlestick
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Candlestick: any;

try {
  const module = await import('../../../adapters/react/candlestick');
  Candlestick = module.Candlestick;
} catch (error) {
  console.warn('React adapter for candlestick not built yet. Run: npm run build:react');
  Candlestick = null;
}

describe('React Adapter: Candlestick', () => {
  if (!Candlestick) {
    it.skip('Candlestick adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Candlestick',
    Component: Candlestick,
    properties: [
      { name: 'showVolume', value: 'test' },
      { name: 'showGrid', value: 'test' },
      { name: 'showCrosshair', value: 'test' },
      { name: 'bullishColor', value: 'test' },
      { name: 'bearishColor', value: 'test' },
      { name: 'timeFormat', value: 'test' },
      { name: 'yAxisFormat', value: 'test' },
      { name: 'zoomEnabled', value: 'test' },
      { name: 'animation', value: 'test' }
    ],
    events: [
      { name: 'onCandleClick' },
      { name: 'onCandleHover' },
      { name: 'onCrosshairMove' }
    ],
    defaultProps: {}
  });
});
