/**
 * React adapter tests for Card
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Card: any;

try {
  const module = await import('../../../adapters/react/card');
  Card = module.Card;
} catch (error) {
  console.warn('React adapter for card not built yet. Run: npm run build:react');
  Card = null;
}

describe('React Adapter: Card', () => {
  if (!Card) {
    it.skip('Card adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Card',
    Component: Card,
    properties: [
      { name: 'clickable', value: 'test' },
      { name: 'disabled', value: true }
    ],
    events: [
      { name: 'onClick' }
    ],
    variants: ["default","outlined","elevated","flat"],
    defaultProps: {}
  });
});
