/**
 * React adapter tests for Carousel
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Carousel: any;

try {
  const module = await import('../../../adapters/react/carousel');
  Carousel = module.Carousel;
} catch (error) {
  console.warn('React adapter for carousel not built yet. Run: npm run build:react');
  Carousel = null;
}

describe('React Adapter: Carousel', () => {
  if (!Carousel) {
    it.skip('Carousel adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Carousel',
    Component: Carousel,
    defaultProps: {}
  });
});
