/**
 * React adapter tests for Cart
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Cart: any;

try {
  const module = await import('../../../adapters/react/cart');
  Cart = module.Cart;
} catch (error) {
  console.warn('React adapter for cart not built yet. Run: npm run build:react');
  Cart = null;
}

describe('React Adapter: Cart', () => {
  if (!Cart) {
    it.skip('Cart adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Cart',
    Component: Cart,
    defaultProps: {}
  });
});
