/**
 * React adapter tests for Chart
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Chart: any;

try {
  const module = await import('../../../adapters/react/chart');
  Chart = module.Chart;
} catch (error) {
  console.warn('React adapter for chart not built yet. Run: npm run build:react');
  Chart = null;
}

describe('React Adapter: Chart', () => {
  if (!Chart) {
    it.skip('Chart adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Chart',
    Component: Chart,
    defaultProps: {}
  });
});
