/**
 * React adapter tests for Chat
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Chat: any;

try {
  const module = await import('../../../adapters/react/chat');
  Chat = module.Chat;
} catch (error) {
  console.warn('React adapter for chat not built yet. Run: npm run build:react');
  Chat = null;
}

describe('React Adapter: Chat', () => {
  if (!Chat) {
    it.skip('Chat adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Chat',
    Component: Chat,
    defaultProps: {}
  });
});
