/**
 * React adapter tests for Checkbox
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Checkbox: any;

try {
  const module = await import('../../../adapters/react/checkbox');
  Checkbox = module.Checkbox;
} catch (error) {
  console.warn('React adapter for checkbox not built yet. Run: npm run build:react');
  Checkbox = null;
}

describe('React Adapter: Checkbox', () => {
  if (!Checkbox) {
    it.skip('Checkbox adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Checkbox',
    Component: Checkbox,
    properties: [
      { name: 'checked', value: 'test' },
      { name: 'indeterminate', value: 'test' }
    ],
    events: [
      { name: 'onChange' }
    ],
    sizes: ["small","medium","large"],
    isForm: true,
    formOptions: {
      valueType: 'boolean',
      defaultValue: false
    },
    defaultProps: {}
  });
});
