/**
 * React adapter tests for Chip
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Chip: any;

try {
  const module = await import('../../../adapters/react/chip');
  Chip = module.Chip;
} catch (error) {
  console.warn('React adapter for chip not built yet. Run: npm run build:react');
  Chip = null;
}

describe('React Adapter: Chip', () => {
  if (!Chip) {
    it.skip('Chip adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Chip',
    Component: Chip,
    properties: [
      { name: 'closable', value: 'test' },
      { name: 'clickable', value: 'test' }
    ],
    events: [
      { name: 'onClick' },
      { name: 'onClose' }
    ],
    variants: ["filled","outlined"],
    sizes: ["small","medium","large"],
    defaultProps: {}
  });
});
