/**
 * React adapter tests for CodeBlock
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let CodeBlock: any;

try {
  const module = await import('../../../adapters/react/code-block');
  CodeBlock = module.CodeBlock;
} catch (error) {
  console.warn('React adapter for code-block not built yet. Run: npm run build:react');
  CodeBlock = null;
}

describe('React Adapter: CodeBlock', () => {
  if (!CodeBlock) {
    it.skip('CodeBlock adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'CodeBlock',
    Component: CodeBlock,
    defaultProps: {}
  });
});
