/**
 * React adapter tests for ColorDisplay
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let ColorDisplay: any;

try {
  const module = await import('../../../adapters/react/color-display');
  ColorDisplay = module.ColorDisplay;
} catch (error) {
  console.warn('React adapter for color-display not built yet. Run: npm run build:react');
  ColorDisplay = null;
}

describe('React Adapter: ColorDisplay', () => {
  if (!ColorDisplay) {
    it.skip('ColorDisplay adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'ColorDisplay',
    Component: ColorDisplay,
    defaultProps: {}
  });
});
