/**
 * React adapter tests for ColorPicker
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let ColorPicker: any;

try {
  const module = await import('../../../adapters/react/color-picker');
  ColorPicker = module.ColorPicker;
} catch (error) {
  console.warn('React adapter for color-picker not built yet. Run: npm run build:react');
  ColorPicker = null;
}

describe('React Adapter: ColorPicker', () => {
  if (!ColorPicker) {
    it.skip('ColorPicker adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'ColorPicker',
    Component: ColorPicker,
    defaultProps: {}
  });
});
