/**
 * React adapter tests for Combobox
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Combobox: any;

try {
  const module = await import('../../../adapters/react/combobox');
  Combobox = module.Combobox;
} catch (error) {
  console.warn('React adapter for combobox not built yet. Run: npm run build:react');
  Combobox = null;
}

describe('React Adapter: Combobox', () => {
  if (!Combobox) {
    it.skip('Combobox adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Combobox',
    Component: Combobox,
    defaultProps: {}
  });
});
