/**
 * React adapter tests for Combobox
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Combobox: any;

try {
  const module = await import('../../../adapters/react/combobox');
  Combobox = module.Combobox;
} catch (error) {
  console.warn('React adapter for combobox not built yet. Run: npm run build:react');
  Combobox = null;
}

describe('React Adapter: Combobox', () => {
  if (!Combobox) {
    it.skip('Combobox adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Combobox',
    Component: Combobox,
    properties: [
      { name: 'value', value: 'option1' },
      { name: 'placeholder', value: 'Select an option' },
      { name: 'allowCustom', value: true },
      { name: 'filterable', value: true },
      { name: 'disabled', value: true },
      { name: 'readonly', value: true },
      { name: 'required', value: true },
      { name: 'name', value: 'test-combobox' },
      { name: 'label', value: 'Test Label' }
    ],
    events: [
      { name: 'onValueChange' },
      { name: 'onInputChange' },
      { name: 'onOptionSelect' }
    ],
    variants: ['default', 'outlined'],
    sizes: ['small', 'medium', 'large'],
    isForm: true,
    formOptions: {
      valueType: 'string',
      defaultValue: ''
    },
    defaultProps: {}
  });
});
