/**
 * React adapter tests for Comments
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Comments: any;

try {
  const module = await import('../../../adapters/react/comments');
  Comments = module.Comments;
} catch (error) {
  console.warn('React adapter for comments not built yet. Run: npm run build:react');
  Comments = null;
}

describe('React Adapter: Comments', () => {
  if (!Comments) {
    it.skip('Comments adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Comments',
    Component: Comments,
    properties: [
      { name: 'currentUser', value: 'test' },
      { name: 'allowReplies', value: 'test' },
      { name: 'allowLikes', value: 'test' },
      { name: 'maxDepth', value: 'test' }
    ],
    events: [
      { name: 'onCommentAdd' },
      { name: 'onCommentReply' },
      { name: 'onCommentDelete' },
      { name: 'onCommentLike' }
    ],
    defaultProps: {}
  });
});
