/**
 * React adapter tests for CommandPalette
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let CommandPalette: any;

try {
  const module = await import('../../../adapters/react/command-palette');
  CommandPalette = module.CommandPalette;
} catch (error) {
  console.warn('React adapter for command-palette not built yet. Run: npm run build:react');
  CommandPalette = null;
}

describe('React Adapter: CommandPalette', () => {
  if (!CommandPalette) {
    it.skip('CommandPalette adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'CommandPalette',
    Component: CommandPalette,
    defaultProps: {}
  });
});
