/**
 * React adapter tests for Countdown
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe, it, expect, vi } from 'vitest';
import { testComponent, testComponentProperties, testComponentEvents } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Countdown: any;

try {
  const module = await import('../../../adapters/react/countdown');
  Countdown = module.Countdown;
} catch (error) {
  console.warn('React adapter for countdown not built yet. Run: npm run build:react');
  Countdown = null;
}

describe('React Adapter: Countdown', () => {
  if (!Countdown) {
    it.skip('Countdown adapter not built', () => {});
    return;
  }

  describe('Basic Component Tests', () => {
    testComponent({
      name: 'Countdown',
      Component: Countdown,
      defaultProps: {}
    });
  });

  describe('Properties', () => {
    testComponentProperties('Countdown', Countdown, [
      { name: 'target', value: '2025-12-31T23:59:59.000Z', type: 'string' },
      { name: 'format', value: 'dhms', type: 'string' },
      { name: 'variant', value: 'simple', type: 'string' },
      { name: 'autostart', value: true, type: 'boolean' }
    ]);

    it('should accept target property for specifying end date', () => {
      const targetDate = '2025-06-15T12:00:00.000Z';
      const element = React.createElement(Countdown, { target: targetDate });
      expect(element).toBeDefined();
      expect(element.props.target).toBe(targetDate);
    });

    it('should accept format property with dhms value', () => {
      const element = React.createElement(Countdown, { format: 'dhms' });
      expect(element.props.format).toBe('dhms');
    });

    it('should accept format property with hms value', () => {
      const element = React.createElement(Countdown, { format: 'hms' });
      expect(element.props.format).toBe('hms');
    });

    it('should accept format property with ms value', () => {
      const element = React.createElement(Countdown, { format: 'ms' });
      expect(element.props.format).toBe('ms');
    });

    it('should accept variant property with flip value', () => {
      const element = React.createElement(Countdown, { variant: 'flip' });
      expect(element.props.variant).toBe('flip');
    });

    it('should accept variant property with circular value', () => {
      const element = React.createElement(Countdown, { variant: 'circular' });
      expect(element.props.variant).toBe('circular');
    });

    it('should accept autostart property', () => {
      const element = React.createElement(Countdown, { autostart: false });
      expect(element.props.autostart).toBe(false);
    });
  });

  describe('Events', () => {
    testComponentEvents('Countdown', Countdown, [
      { name: 'onCountdownTick', trigger: 'countdown-tick' },
      { name: 'onCountdownComplete', trigger: 'countdown-complete' }
    ]);

    it('should accept onCountdownTick callback', () => {
      const handler = vi.fn();
      const element = React.createElement(Countdown, { onCountdownTick: handler });
      expect(element).toBeDefined();
      expect(element.props.onCountdownTick).toBe(handler);
    });

    it('should accept onCountdownComplete callback', () => {
      const handler = vi.fn();
      const element = React.createElement(Countdown, { onCountdownComplete: handler });
      expect(element).toBeDefined();
      expect(element.props.onCountdownComplete).toBe(handler);
    });

    it('should handle multiple event handlers', () => {
      const tickHandler = vi.fn();
      const completeHandler = vi.fn();
      const element = React.createElement(Countdown, {
        onCountdownTick: tickHandler,
        onCountdownComplete: completeHandler
      });
      expect(element).toBeDefined();
      expect(element.props.onCountdownTick).toBe(tickHandler);
      expect(element.props.onCountdownComplete).toBe(completeHandler);
    });
  });

  describe('Combined Props', () => {
    it('should handle all properties together', () => {
      const targetDate = '2025-12-31T23:59:59.000Z';
      const tickHandler = vi.fn();
      const completeHandler = vi.fn();
      
      const element = React.createElement(Countdown, {
        target: targetDate,
        format: 'dhms',
        variant: 'flip',
        autostart: true,
        onCountdownTick: tickHandler,
        onCountdownComplete: completeHandler
      });
      
      expect(element).toBeDefined();
      expect(element.props.target).toBe(targetDate);
      expect(element.props.format).toBe('dhms');
      expect(element.props.variant).toBe('flip');
      expect(element.props.autostart).toBe(true);
      expect(element.props.onCountdownTick).toBe(tickHandler);
      expect(element.props.onCountdownComplete).toBe(completeHandler);
    });
  });
});

// Need to import React for the test-helpers functions
import React from 'react';
