/**
 * React adapter tests for Countdown
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Countdown: any;

try {
  const module = await import('../../../adapters/react/countdown');
  Countdown = module.Countdown;
} catch (error) {
  console.warn('React adapter for countdown not built yet. Run: npm run build:react');
  Countdown = null;
}

describe('React Adapter: Countdown', () => {
  if (!Countdown) {
    it.skip('Countdown adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Countdown',
    Component: Countdown,
    defaultProps: {}
  });
});
