/**
 * React adapter tests for Cropper
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe, it, expect, vi } from 'vitest';
import { testComponent, testComponentProperties, testComponentEvents } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Cropper: any;

try {
  const module = await import('../../../adapters/react/cropper');
  Cropper = module.Cropper;
} catch (error) {
  console.warn('React adapter for cropper not built yet. Run: npm run build:react');
  Cropper = null;
}

describe('React Adapter: Cropper', () => {
  if (!Cropper) {
    it.skip('Cropper adapter not built', () => {});
    return;
  }

  describe('Basic Component Tests', () => {
    testComponent({
      name: 'Cropper',
      Component: Cropper,
      defaultProps: {}
    });
  });

  describe('Properties', () => {
    testComponentProperties('Cropper', Cropper, [
      { name: 'src', value: 'https://example.com/image.jpg', type: 'string' },
      { name: 'aspectRatio', value: 16 / 9, type: 'number' },
      { name: 'aspectRatio', value: 1, type: 'number' },
      { name: 'aspectRatio', value: 4 / 3, type: 'number' },
      { name: 'minWidth', value: 100, type: 'number' },
      { name: 'minHeight', value: 100, type: 'number' },
      { name: 'outputType', value: 'blob', type: 'string' },
      { name: 'outputType', value: 'base64', type: 'string' },
      { name: 'outputType', value: 'file', type: 'string' }
    ]);

    it('should accept src property for image URL', () => {
      const src = 'https://example.com/photo.png';
      const element = React.createElement(Cropper, { src });
      expect(element).toBeDefined();
      expect(element.props.src).toBe(src);
    });

    it('should accept aspectRatio property', () => {
      const element = React.createElement(Cropper, { aspectRatio: 16 / 9 });
      expect(element.props.aspectRatio).toBe(16 / 9);
    });

    it('should accept square aspectRatio', () => {
      const element = React.createElement(Cropper, { aspectRatio: 1 });
      expect(element.props.aspectRatio).toBe(1);
    });

    it('should accept minWidth property', () => {
      const element = React.createElement(Cropper, { minWidth: 200 });
      expect(element.props.minWidth).toBe(200);
    });

    it('should accept minHeight property', () => {
      const element = React.createElement(Cropper, { minHeight: 150 });
      expect(element.props.minHeight).toBe(150);
    });

    it('should accept outputType property with blob', () => {
      const element = React.createElement(Cropper, { outputType: 'blob' });
      expect(element.props.outputType).toBe('blob');
    });

    it('should accept outputType property with base64', () => {
      const element = React.createElement(Cropper, { outputType: 'base64' });
      expect(element.props.outputType).toBe('base64');
    });

    it('should accept outputType property with file', () => {
      const element = React.createElement(Cropper, { outputType: 'file' });
      expect(element.props.outputType).toBe('file');
    });
  });

  describe('Combined Props', () => {
    it('should handle all properties together', () => {
      const element = React.createElement(Cropper, {
        src: 'https://example.com/image.jpg',
        aspectRatio: 16 / 9,
        minWidth: 200,
        minHeight: 150,
        outputType: 'base64'
      });
      
      expect(element).toBeDefined();
      expect(element.props.src).toBe('https://example.com/image.jpg');
      expect(element.props.aspectRatio).toBe(16 / 9);
      expect(element.props.minWidth).toBe(200);
      expect(element.props.minHeight).toBe(150);
      expect(element.props.outputType).toBe('base64');
    });
  });
});

// Need to import React for the test-helpers functions
import React from 'react';
