/**
 * React adapter tests for Cropper
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Cropper: any;

try {
  const module = await import('../../../adapters/react/cropper');
  Cropper = module.Cropper;
} catch (error) {
  console.warn('React adapter for cropper not built yet. Run: npm run build:react');
  Cropper = null;
}

describe('React Adapter: Cropper', () => {
  if (!Cropper) {
    it.skip('Cropper adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Cropper',
    Component: Cropper,
    defaultProps: {}
  });
});
