/**
 * React adapter tests for DataCard
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let DataCard: any;

try {
  const module = await import('../../../adapters/react/data-card');
  DataCard = module.DataCard;
} catch (error) {
  console.warn('React adapter for data-card not built yet. Run: npm run build:react');
  DataCard = null;
}

describe('React Adapter: DataCard', () => {
  if (!DataCard) {
    it.skip('DataCard adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'DataCard',
    Component: DataCard,
    defaultProps: {}
  });
});
