/**
 * React adapter tests for DatePicker
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let DatePicker: any;

try {
  const module = await import('../../../adapters/react/date-picker');
  DatePicker = module.DatePicker;
} catch (error) {
  console.warn('React adapter for date-picker not built yet. Run: npm run build:react');
  DatePicker = null;
}

describe('React Adapter: DatePicker', () => {
  if (!DatePicker) {
    it.skip('DatePicker adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'DatePicker',
    Component: DatePicker,
    defaultProps: {}
  });
});
