/**
 * React adapter tests for DateRangePicker
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let DateRangePicker: any;

try {
  const module = await import('../../../adapters/react/date-range-picker');
  DateRangePicker = module.DateRangePicker;
} catch (error) {
  console.warn('React adapter for date-range-picker not built yet. Run: npm run build:react');
  DateRangePicker = null;
}

describe('React Adapter: DateRangePicker', () => {
  if (!DateRangePicker) {
    it.skip('DateRangePicker adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'DateRangePicker',
    Component: DateRangePicker,
    defaultProps: {}
  });
});
