/**
 * React adapter tests for DateTimePicker
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let DateTimePicker: any;

try {
  const module = await import('../../../adapters/react/date-time-picker');
  DateTimePicker = module.DateTimePicker;
} catch (error) {
  console.warn('React adapter for date-time-picker not built yet. Run: npm run build:react');
  DateTimePicker = null;
}

describe('React Adapter: DateTimePicker', () => {
  if (!DateTimePicker) {
    it.skip('DateTimePicker adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'DateTimePicker',
    Component: DateTimePicker,
    defaultProps: {}
  });
});
