/**
 * React adapter tests for Diff
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe, it, expect, vi } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Diff: any;

try {
  const module = await import('../../../adapters/react/diff');
  Diff = module.Diff;
} catch (error) {
  console.warn('React adapter for diff not built yet. Run: npm run build:react');
  Diff = null;
}

describe('React Adapter: Diff', () => {
  if (!Diff) {
    it.skip('Diff adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Diff',
    Component: Diff,
    defaultProps: {}
  });

  describe('Diff - Properties', () => {
    it('should accept oldText property', () => {
      const element = React.createElement(Diff, { oldText: 'old content' });
      expect(element).toBeDefined();
      expect(element.props.oldText).toBe('old content');
    });

    it('should accept newText property', () => {
      const element = React.createElement(Diff, { newText: 'new content' });
      expect(element).toBeDefined();
      expect(element.props.newText).toBe('new content');
    });

    it('should accept mode property', () => {
      const element = React.createElement(Diff, { mode: 'split' });
      expect(element).toBeDefined();
      expect(element.props.mode).toBe('split');
    });

    it('should accept unified mode', () => {
      const element = React.createElement(Diff, { mode: 'unified' });
      expect(element).toBeDefined();
      expect(element.props.mode).toBe('unified');
    });

    it('should accept language property', () => {
      const languages = ['javascript', 'typescript', 'json', 'html', 'css', 'python'];
      
      languages.forEach(lang => {
        const element = React.createElement(Diff, { language: lang });
        expect(element).toBeDefined();
        expect(element.props.language).toBe(lang);
      });
    });

    it('should accept lineNumbers property', () => {
      const element = React.createElement(Diff, { lineNumbers: true });
      expect(element).toBeDefined();
      expect(element.props.lineNumbers).toBe(true);
    });

    it('should accept contextLines property', () => {
      const element = React.createElement(Diff, { contextLines: 5 });
      expect(element).toBeDefined();
      expect(element.props.contextLines).toBe(5);
    });

    it('should accept markers property', () => {
      const element = React.createElement(Diff, { markers: false });
      expect(element).toBeDefined();
      expect(element.props.markers).toBe(false);
    });

    it('should handle multiple properties at once', () => {
      const props = {
        oldText: 'original code',
        newText: 'modified code',
        mode: 'split',
        language: 'javascript',
        lineNumbers: true,
        contextLines: 3
      };
      const element = React.createElement(Diff, props);
      expect(element).toBeDefined();
      expect(element.props.oldText).toBe('original code');
      expect(element.props.newText).toBe('modified code');
      expect(element.props.mode).toBe('split');
      expect(element.props.language).toBe('javascript');
      expect(element.props.lineNumbers).toBe(true);
      expect(element.props.contextLines).toBe(3);
    });
  });

  describe('Diff - Events', () => {
    it('should accept onDiffComputed callback', () => {
      const handler = vi.fn();
      const element = React.createElement(Diff, { onDiffComputed: handler });
      expect(element).toBeDefined();
      expect(element.props.onDiffComputed).toBe(handler);
    });

    it('should handle event handlers', () => {
      const diffHandler = vi.fn();
      const props = { onDiffComputed: diffHandler };
      const element = React.createElement(Diff, props);
      expect(element).toBeDefined();
    });
  });
});

// Import React for element creation
import React from 'react';
