/**
 * React adapter tests for Diff
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Diff: any;

try {
  const module = await import('../../../adapters/react/diff');
  Diff = module.Diff;
} catch (error) {
  console.warn('React adapter for diff not built yet. Run: npm run build:react');
  Diff = null;
}

describe('React Adapter: Diff', () => {
  if (!Diff) {
    it.skip('Diff adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Diff',
    Component: Diff,
    defaultProps: {}
  });
});
