/**
 * React adapter tests for Divider
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Divider: any;

try {
  const module = await import('../../../adapters/react/divider');
  Divider = module.Divider;
} catch (error) {
  console.warn('React adapter for divider not built yet. Run: npm run build:react');
  Divider = null;
}

describe('React Adapter: Divider', () => {
  if (!Divider) {
    it.skip('Divider adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Divider',
    Component: Divider,
    defaultProps: {}
  });
});
