/**
 * React adapter tests for Doc
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Doc: any;

try {
  const module = await import('../../../adapters/react/doc');
  Doc = module.Doc;
} catch (error) {
  console.warn('React adapter for doc not built yet. Run: npm run build:react');
  Doc = null;
}

describe('React Adapter: Doc', () => {
  if (!Doc) {
    it.skip('Doc adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Doc',
    Component: Doc,
    defaultProps: {}
  });
});
