/**
 * React adapter tests for Draw
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Draw: any;

try {
  const module = await import('../../../adapters/react/draw');
  Draw = module.Draw;
} catch (error) {
  console.warn('React adapter for draw not built yet. Run: npm run build:react');
  Draw = null;
}

describe('React Adapter: Draw', () => {
  if (!Draw) {
    it.skip('Draw adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Draw',
    Component: Draw,
    defaultProps: {}
  });
});
