/**
 * React adapter tests for Drawer
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Drawer: any;

try {
  const module = await import('../../../adapters/react/drawer');
  Drawer = module.Drawer;
} catch (error) {
  console.warn('React adapter for drawer not built yet. Run: npm run build:react');
  Drawer = null;
}

describe('React Adapter: Drawer', () => {
  if (!Drawer) {
    it.skip('Drawer adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Drawer',
    Component: Drawer,
    properties: [
      { name: 'open', value: 'test' },
      { name: 'position', value: 'top' }
    ],
    events: [
      { name: 'onClose' },
      { name: 'onOpen' }
    ],
    defaultProps: {}
  });
});
