/**
 * React adapter tests for EmptyState
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let EmptyState: any;

try {
  const module = await import('../../../adapters/react/empty-state');
  EmptyState = module.EmptyState;
} catch (error) {
  console.warn('React adapter for empty-state not built yet. Run: npm run build:react');
  EmptyState = null;
}

describe('React Adapter: EmptyState', () => {
  if (!EmptyState) {
    it.skip('EmptyState adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'EmptyState',
    Component: EmptyState,
    defaultProps: {}
  });
});
