/**
 * React adapter tests for Estimate
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Estimate: any;

try {
  const module = await import('../../../adapters/react/estimate');
  Estimate = module.Estimate;
} catch (error) {
  console.warn('React adapter for estimate not built yet. Run: npm run build:react');
  Estimate = null;
}

describe('React Adapter: Estimate', () => {
  if (!Estimate) {
    it.skip('Estimate adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Estimate',
    Component: Estimate,
    defaultProps: {}
  });
});
