/**
 * React adapter tests for FileUpload
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let FileUpload: any;

try {
  const module = await import('../../../adapters/react/file-upload');
  FileUpload = module.FileUpload;
} catch (error) {
  console.warn('React adapter for file-upload not built yet. Run: npm run build:react');
  FileUpload = null;
}

describe('React Adapter: FileUpload', () => {
  if (!FileUpload) {
    it.skip('FileUpload adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'FileUpload',
    Component: FileUpload,
    defaultProps: {}
  });
});
