/**
 * React adapter tests for FileGallery
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let FileGallery: any;

try {
  const module = await import('../../../adapters/react/file-gallery');
  FileGallery = module.FileGallery;
} catch (error) {
  console.warn('React adapter for file-gallery not built yet. Run: npm run build:react');
  FileGallery = null;
}

describe('React Adapter: FileGallery', () => {
  if (!FileGallery) {
    it.skip('FileGallery adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'FileGallery',
    Component: FileGallery,
    defaultProps: {}
  });
});
