/**
 * React adapter tests for FlipCard
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let FlipCard: any;

try {
  const module = await import('../../../adapters/react/flip-card');
  FlipCard = module.FlipCard;
} catch (error) {
  console.warn('React adapter for flip-card not built yet. Run: npm run build:react');
  FlipCard = null;
}

describe('React Adapter: FlipCard', () => {
  if (!FlipCard) {
    it.skip('FlipCard adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'FlipCard',
    Component: FlipCard,
    defaultProps: {}
  });
});
