/**
 * React adapter tests for FormLayout
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let FormLayout: any;

try {
  const module = await import('../../../adapters/react/form-layout');
  FormLayout = module.FormLayout;
} catch (error) {
  console.warn('React adapter for form-layout not built yet. Run: npm run build:react');
  FormLayout = null;
}

describe('React Adapter: FormLayout', () => {
  if (!FormLayout) {
    it.skip('FormLayout adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'FormLayout',
    Component: FormLayout,
    defaultProps: {}
  });
});
