/**
 * React adapter tests for FormBuilder
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let FormBuilder: any;

try {
  const module = await import('../../../adapters/react/form-builder');
  FormBuilder = module.FormBuilder;
} catch (error) {
  console.warn('React adapter for form-builder not built yet. Run: npm run build:react');
  FormBuilder = null;
}

describe('React Adapter: FormBuilder', () => {
  if (!FormBuilder) {
    it.skip('FormBuilder adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'FormBuilder',
    Component: FormBuilder,
    defaultProps: {}
  });
});
