/**
 * React adapter tests for Funnel
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Funnel: any;

try {
  const module = await import('../../../adapters/react/funnel');
  Funnel = module.Funnel;
} catch (error) {
  console.warn('React adapter for funnel not built yet. Run: npm run build:react');
  Funnel = null;
}

describe('React Adapter: Funnel', () => {
  if (!Funnel) {
    it.skip('Funnel adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Funnel',
    Component: Funnel,
    properties: [
      { name: 'variant', value: 'test' },
      { name: 'orientation', value: 'test' },
      { name: 'showLabels', value: 'test' },
      { name: 'showValues', value: 'test' },
      { name: 'showPercentages', value: 'test' },
      { name: 'animation', value: 'test' }
    ],
    events: [
      { name: 'onFunnelClick' },
      { name: 'onFunnelHover' }
    ],
    variants: ["default","gradient"],
    defaultProps: {}
  });
});
