/**
 * React adapter tests for Gantt
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Gantt: any;

try {
  const module = await import('../../../adapters/react/gantt');
  Gantt = module.Gantt;
} catch (error) {
  console.warn('React adapter for gantt not built yet. Run: npm run build:react');
  Gantt = null;
}

describe('React Adapter: Gantt', () => {
  if (!Gantt) {
    it.skip('Gantt adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Gantt',
    Component: Gantt,
    defaultProps: {}
  });
});
