/**
 * React adapter tests for Gauge
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Gauge: any;

try {
  const module = await import('../../../adapters/react/gauge');
  Gauge = module.Gauge;
} catch (error) {
  console.warn('React adapter for gauge not built yet. Run: npm run build:react');
  Gauge = null;
}

describe('React Adapter: Gauge', () => {
  if (!Gauge) {
    it.skip('Gauge adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Gauge',
    Component: Gauge,
    defaultProps: {}
  });
});
