/**
 * React adapter tests for Grid
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Grid: any;

try {
  const module = await import('../../../adapters/react/grid');
  Grid = module.Grid;
} catch (error) {
  console.warn('React adapter for grid not built yet. Run: npm run build:react');
  Grid = null;
}

describe('React Adapter: Grid', () => {
  if (!Grid) {
    it.skip('Grid adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Grid',
    Component: Grid,
    properties: [
      { name: 'gap', value: 'test' },
      { name: 'columnWidth', value: 'test' },
      { name: 'rowHeight', value: 'test' },
      { name: 'columns', value: 'test' },
      { name: 'rows', value: 5 },
      { name: 'originLeft', value: 'test' },
      { name: 'originTop', value: 'test' },
      { name: 'transitionDuration', value: 'test' },
      { name: 'stagger', value: 'test' },
      { name: 'resize', value: 'vertical' },
      { name: 'draggable', value: 'test' },
      { name: 'dragThrottle', value: 'test' }
    ],
    events: [
      { name: 'onGridLayoutComplete' },
      { name: 'onGridDragItemPositioned' }
    ],
    defaultProps: {}
  });
});
