/**
 * React adapter tests for Heatmap
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Heatmap: any;

try {
  const module = await import('../../../adapters/react/heatmap');
  Heatmap = module.Heatmap;
} catch (error) {
  console.warn('React adapter for heatmap not built yet. Run: npm run build:react');
  Heatmap = null;
}

describe('React Adapter: Heatmap', () => {
  if (!Heatmap) {
    it.skip('Heatmap adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Heatmap',
    Component: Heatmap,
    defaultProps: {}
  });
});
