/**
 * React adapter tests for Icon
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Icon: any;

try {
  const module = await import('../../../adapters/react/icon');
  Icon = module.Icon;
} catch (error) {
  console.warn('React adapter for icon not built yet. Run: npm run build:react');
  Icon = null;
}

describe('React Adapter: Icon', () => {
  if (!Icon) {
    it.skip('Icon adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Icon',
    Component: Icon,
    properties: [
      { name: 'name', value: 'star' },
      { name: 'src', value: '/path/to/icon.svg' },
      { name: 'size', value: 'medium' },
      { name: 'color', value: 'blue' },
      { name: 'label', value: 'Star icon' }
    ],
    sizes: ['small', 'medium', 'large'],
    defaultProps: {}
  });
});
