/**
 * React adapter tests for Image
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Image: any;

try {
  const module = await import('../../../adapters/react/image');
  Image = module.Image;
} catch (error) {
  console.warn('React adapter for image not built yet. Run: npm run build:react');
  Image = null;
}

describe('React Adapter: Image', () => {
  if (!Image) {
    it.skip('Image adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Image',
    Component: Image,
    defaultProps: {}
  });
});
