/**
 * React adapter tests for Input
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Input: any;

try {
  const module = await import('../../../adapters/react/input');
  Input = module.Input;
} catch (error) {
  console.warn('React adapter for input not built yet. Run: npm run build:react');
  Input = null;
}

describe('React Adapter: Input', () => {
  if (!Input) {
    it.skip('Input adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Input',
    Component: Input,
    properties: [
      { name: 'type', value: 'text' },
      { name: 'placeholder', value: 'Test placeholder' },
      { name: 'minlength', value: 100 },
      { name: 'maxlength', value: 100 },
      { name: 'readonly', value: true }
    ],
    events: [
      { name: 'onInput' },
      { name: 'onChange' },
      { name: 'onFocus' },
      { name: 'onBlur' }
    ],
    variants: ["outlined","filled","underlined"],
    sizes: ["small","medium","large"],
    isForm: true,
    formOptions: {
      valueType: 'string',
      defaultValue: 'test'
    },
    defaultProps: {}
  });
});
