/**
 * React adapter tests for Kanban
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Kanban: any;

try {
  const module = await import('../../../adapters/react/kanban');
  Kanban = module.Kanban;
} catch (error) {
  console.warn('React adapter for kanban not built yet. Run: npm run build:react');
  Kanban = null;
}

describe('React Adapter: Kanban', () => {
  if (!Kanban) {
    it.skip('Kanban adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Kanban',
    Component: Kanban,
    defaultProps: {}
  });
});
