/**
 * React adapter tests for KeyValue
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let KeyValue: any;

try {
  const module = await import('../../../adapters/react/key-value');
  KeyValue = module.KeyValue;
} catch (error) {
  console.warn('React adapter for key-value not built yet. Run: npm run build:react');
  KeyValue = null;
}

describe('React Adapter: KeyValue', () => {
  if (!KeyValue) {
    it.skip('KeyValue adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'KeyValue',
    Component: KeyValue,
    properties: [
      { name: 'label', value: 'test' },
      { name: 'autoExpand', value: 'test' },
      { name: 'rows', value: 5 },
      { name: 'showDescription', value: 'test' },
      { name: 'keyPlaceholder', value: 'test' },
      { name: 'valuePlaceholder', value: 'test' },
      { name: 'disabled', value: true },
      { name: 'readonly', value: true },
      { name: 'name', value: 'test' },
      { name: 'mode', value: 'test' },
      { name: 'showCopy', value: 'test' }
    ],
    events: [
      { name: 'onKvAdd' },
      { name: 'onKvRemove' },
      { name: 'onKvChange' },
      { name: 'onKvCopy' }
    ],
    variants: ["default","compact"],
    isForm: true,
    formOptions: {
      valueType: 'string',
      defaultValue: 'test'
    },
    defaultProps: {}
  });
});
