/**
 * React adapter tests for Kpi
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Kpi: any;

try {
  const module = await import('../../../adapters/react/kpi');
  Kpi = module.Kpi;
} catch (error) {
  console.warn('React adapter for kpi not built yet. Run: npm run build:react');
  Kpi = null;
}

describe('React Adapter: Kpi', () => {
  if (!Kpi) {
    it.skip('Kpi adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Kpi',
    Component: Kpi,
    defaultProps: {}
  });
});
