/**
 * React adapter tests for Layout
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Layout: any;

try {
  const module = await import('../../../adapters/react/layout');
  Layout = module.Layout;
} catch (error) {
  console.warn('React adapter for layout not built yet. Run: npm run build:react');
  Layout = null;
}

describe('React Adapter: Layout', () => {
  if (!Layout) {
    it.skip('Layout adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Layout',
    Component: Layout,
    defaultProps: {}
  });
});
