/**
 * React adapter tests for Leaderboard
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Leaderboard: any;

try {
  const module = await import('../../../adapters/react/leaderboard');
  Leaderboard = module.Leaderboard;
} catch (error) {
  console.warn('React adapter for leaderboard not built yet. Run: npm run build:react');
  Leaderboard = null;
}

describe('React Adapter: Leaderboard', () => {
  if (!Leaderboard) {
    it.skip('Leaderboard adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Leaderboard',
    Component: Leaderboard,
    defaultProps: {}
  });
});
