/**
 * React adapter tests for LinkPreview
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let LinkPreview: any;

try {
  const module = await import('../../../adapters/react/link-preview');
  LinkPreview = module.LinkPreview;
} catch (error) {
  console.warn('React adapter for link-preview not built yet. Run: npm run build:react');
  LinkPreview = null;
}

describe('React Adapter: LinkPreview', () => {
  if (!LinkPreview) {
    it.skip('LinkPreview adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'LinkPreview',
    Component: LinkPreview,
    defaultProps: {}
  });
});
