/**
 * React adapter tests for Link
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Link: any;

try {
  const module = await import('../../../adapters/react/link');
  Link = module.Link;
} catch (error) {
  console.warn('React adapter for link not built yet. Run: npm run build:react');
  Link = null;
}

describe('React Adapter: Link', () => {
  if (!Link) {
    it.skip('Link adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Link',
    Component: Link,
    defaultProps: {}
  });
});
