/**
 * React adapter tests for Location
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Location: any;

try {
  const module = await import('../../../adapters/react/location');
  Location = module.Location;
} catch (error) {
  console.warn('React adapter for location not built yet. Run: npm run build:react');
  Location = null;
}

describe('React Adapter: Location', () => {
  if (!Location) {
    it.skip('Location adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Location',
    Component: Location,
    defaultProps: {}
  });
});
