/**
 * React adapter tests for Login
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Login: any;

try {
  const module = await import('../../../adapters/react/login');
  Login = module.Login;
} catch (error) {
  console.warn('React adapter for login not built yet. Run: npm run build:react');
  Login = null;
}

describe('React Adapter: Login', () => {
  if (!Login) {
    it.skip('Login adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Login',
    Component: Login,
    defaultProps: {}
  });
});
