/**
 * React adapter tests for Map
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Map: any;

try {
  const module = await import('../../../adapters/react/map');
  Map = module.Map;
} catch (error) {
  console.warn('React adapter for map not built yet. Run: npm run build:react');
  Map = null;
}

describe('React Adapter: Map', () => {
  if (!Map) {
    it.skip('Map adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Map',
    Component: Map,
    defaultProps: {}
  });
});
