/**
 * React adapter tests for Markdown
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Markdown: any;

try {
  const module = await import('../../../adapters/react/markdown');
  Markdown = module.Markdown;
} catch (error) {
  console.warn('React adapter for markdown not built yet. Run: npm run build:react');
  Markdown = null;
}

describe('React Adapter: Markdown', () => {
  if (!Markdown) {
    it.skip('Markdown adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Markdown',
    Component: Markdown,
    defaultProps: {}
  });
});
