/**
 * React adapter tests for Masonry
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Masonry: any;

try {
  const module = await import('../../../adapters/react/masonry');
  Masonry = module.Masonry;
} catch (error) {
  console.warn('React adapter for masonry not built yet. Run: npm run build:react');
  Masonry = null;
}

describe('React Adapter: Masonry', () => {
  if (!Masonry) {
    it.skip('Masonry adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Masonry',
    Component: Masonry,
    defaultProps: {}
  });
});
