/**
 * React adapter tests for Mentions
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Mentions: any;

try {
  const module = await import('../../../adapters/react/mentions');
  Mentions = module.Mentions;
} catch (error) {
  console.warn('React adapter for mentions not built yet. Run: npm run build:react');
  Mentions = null;
}

describe('React Adapter: Mentions', () => {
  if (!Mentions) {
    it.skip('Mentions adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Mentions',
    Component: Mentions,
    defaultProps: {}
  });
});
