/**
 * React adapter tests for Menu
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Menu: any;

try {
  const module = await import('../../../adapters/react/menu');
  Menu = module.Menu;
} catch (error) {
  console.warn('React adapter for menu not built yet. Run: npm run build:react');
  Menu = null;
}

describe('React Adapter: Menu', () => {
  if (!Menu) {
    it.skip('Menu adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Menu',
    Component: Menu,
    defaultProps: {}
  });
});
