/**
 * React adapter tests for MessageStrip
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let MessageStrip: any;

try {
  const module = await import('../../../adapters/react/message-strip');
  MessageStrip = module.MessageStrip;
} catch (error) {
  console.warn('React adapter for message-strip not built yet. Run: npm run build:react');
  MessageStrip = null;
}

describe('React Adapter: MessageStrip', () => {
  if (!MessageStrip) {
    it.skip('MessageStrip adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'MessageStrip',
    Component: MessageStrip,
    defaultProps: {}
  });
});
