/**
 * React adapter tests for MetricTable
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let MetricTable: any;

try {
  const module = await import('../../../adapters/react/metric-table');
  MetricTable = module.MetricTable;
} catch (error) {
  console.warn('React adapter for metric-table not built yet. Run: npm run build:react');
  MetricTable = null;
}

describe('React Adapter: MetricTable', () => {
  if (!MetricTable) {
    it.skip('MetricTable adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'MetricTable',
    Component: MetricTable,
    defaultProps: {}
  });
});
