/**
 * React adapter tests for Modal
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Modal: any;

try {
  const module = await import('../../../adapters/react/modal');
  Modal = module.Modal;
} catch (error) {
  console.warn('React adapter for modal not built yet. Run: npm run build:react');
  Modal = null;
}

describe('React Adapter: Modal', () => {
  if (!Modal) {
    it.skip('Modal adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Modal',
    Component: Modal,
    properties: [
      { name: 'open', value: 'test' },
      { name: 'closeOnEscape', value: 'test' },
      { name: 'closeOnOutsideClick', value: 'test' }
    ],
    events: [
      { name: 'onClose' },
      { name: 'onOpen' }
    ],
    defaultProps: {}
  });
});
