/**
 * React adapter tests for MusicPlayer
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let MusicPlayer: any;

try {
  const module = await import('../../../adapters/react/music-player');
  MusicPlayer = module.MusicPlayer;
} catch (error) {
  console.warn('React adapter for music-player not built yet. Run: npm run build:react');
  MusicPlayer = null;
}

describe('React Adapter: MusicPlayer', () => {
  if (!MusicPlayer) {
    it.skip('MusicPlayer adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'MusicPlayer',
    Component: MusicPlayer,
    defaultProps: {}
  });
});
