/**
 * React adapter tests for Nav
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Nav: any;

try {
  const module = await import('../../../adapters/react/nav');
  Nav = module.Nav;
} catch (error) {
  console.warn('React adapter for nav not built yet. Run: npm run build:react');
  Nav = null;
}

describe('React Adapter: Nav', () => {
  if (!Nav) {
    it.skip('Nav adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Nav',
    Component: Nav,
    defaultProps: {}
  });
});
