/**
 * React adapter tests for NetworkGraph
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let NetworkGraph: any;

try {
  const module = await import('../../../adapters/react/network-graph');
  NetworkGraph = module.NetworkGraph;
} catch (error) {
  console.warn('React adapter for network-graph not built yet. Run: npm run build:react');
  NetworkGraph = null;
}

describe('React Adapter: NetworkGraph', () => {
  if (!NetworkGraph) {
    it.skip('NetworkGraph adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'NetworkGraph',
    Component: NetworkGraph,
    properties: [
      { name: 'layout', value: 'test' },
      { name: 'chargeStrength', value: 'test' },
      { name: 'linkDistance', value: 'test' },
      { name: 'zoomEnabled', value: 'test' },
      { name: 'dragEnabled', value: 'test' },
      { name: 'showLabels', value: 'test' },
      { name: 'animation', value: 'test' }
    ],
    events: [
      { name: 'onNodeClick' },
      { name: 'onEdgeClick' },
      { name: 'onNodeDrag' },
      { name: 'onGraphZoom' }
    ],
    defaultProps: {}
  });
});
