/**
 * React adapter tests for NotificationCenter
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let NotificationCenter: any;

try {
  const module = await import('../../../adapters/react/notification-center');
  NotificationCenter = module.NotificationCenter;
} catch (error) {
  console.warn('React adapter for notification-center not built yet. Run: npm run build:react');
  NotificationCenter = null;
}

describe('React Adapter: NotificationCenter', () => {
  if (!NotificationCenter) {
    it.skip('NotificationCenter adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'NotificationCenter',
    Component: NotificationCenter,
    defaultProps: {}
  });
});
