/**
 * React adapter tests for NotificationCenter
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe, it, expect, vi } from 'vitest';
import { testComponent, testComponentProperties, testComponentEvents } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let NotificationCenter: any;

try {
  const module = await import('../../../adapters/react/notification-center');
  NotificationCenter = module.NotificationCenter;
} catch (error) {
  console.warn('React adapter for notification-center not built yet. Run: npm run build:react');
  NotificationCenter = null;
}

describe('React Adapter: NotificationCenter', () => {
  if (!NotificationCenter) {
    it.skip('NotificationCenter adapter not built', () => {});
    return;
  }

  describe('Basic Component Tests', () => {
    testComponent({
      name: 'NotificationCenter',
      Component: NotificationCenter,
      defaultProps: {}
    });
  });

  describe('Properties', () => {
    testComponentProperties('NotificationCenter', NotificationCenter, [
      { name: 'notifications', value: [{ id: 1, message: 'Test notification' }], type: 'object' },
      { name: 'open', value: true, type: 'boolean' },
      { name: 'open', value: false, type: 'boolean' }
    ]);

    it('should accept notifications array property', () => {
      const notifications = [
        { id: 1, message: 'First notification', type: 'info' },
        { id: 2, message: 'Second notification', type: 'success' }
      ];
      const element = React.createElement(NotificationCenter, { notifications });
      expect(element).toBeDefined();
      expect(element.props.notifications).toBe(notifications);
    });

    it('should accept empty notifications array', () => {
      const element = React.createElement(NotificationCenter, { notifications: [] });
      expect(element).toBeDefined();
      expect(element.props.notifications).toEqual([]);
    });

    it('should accept open boolean property', () => {
      const element = React.createElement(NotificationCenter, { open: true });
      expect(element.props.open).toBe(true);
    });

    it('should accept closed state', () => {
      const element = React.createElement(NotificationCenter, { open: false });
      expect(element.props.open).toBe(false);
    });
  });

  describe('Combined Props', () => {
    it('should handle all properties together', () => {
      const notifications = [
        { id: '1', title: 'Welcome', message: 'Thanks for joining!', type: 'success', read: false },
        { id: '2', title: 'Reminder', message: 'Meeting in 10 minutes', type: 'warning', read: true }
      ];
      
      const element = React.createElement(NotificationCenter, {
        notifications,
        open: true
      });
      
      expect(element).toBeDefined();
      expect(element.props.notifications).toBe(notifications);
      expect(element.props.open).toBe(true);
    });

    it('should handle open notification center with no notifications', () => {
      const element = React.createElement(NotificationCenter, {
        notifications: [],
        open: true
      });
      
      expect(element).toBeDefined();
      expect(element.props.notifications).toEqual([]);
      expect(element.props.open).toBe(true);
    });
  });
});

// Need to import React for the test-helpers functions
import React from 'react';
