/**
 * React adapter tests for OrderTracker
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let OrderTracker: any;

try {
  const module = await import('../../../adapters/react/order-tracker');
  OrderTracker = module.OrderTracker;
} catch (error) {
  console.warn('React adapter for order-tracker not built yet. Run: npm run build:react');
  OrderTracker = null;
}

describe('React Adapter: OrderTracker', () => {
  if (!OrderTracker) {
    it.skip('OrderTracker adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'OrderTracker',
    Component: OrderTracker,
    defaultProps: {}
  });
});
