/**
 * React adapter tests for OrgChart
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let OrgChart: any;

try {
  const module = await import('../../../adapters/react/org-chart');
  OrgChart = module.OrgChart;
} catch (error) {
  console.warn('React adapter for org-chart not built yet. Run: npm run build:react');
  OrgChart = null;
}

describe('React Adapter: OrgChart', () => {
  if (!OrgChart) {
    it.skip('OrgChart adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'OrgChart',
    Component: OrgChart,
    defaultProps: {}
  });
});
