/**
 * React adapter tests for Pagination
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Pagination: any;

try {
  const module = await import('../../../adapters/react/pagination');
  Pagination = module.Pagination;
} catch (error) {
  console.warn('React adapter for pagination not built yet. Run: npm run build:react');
  Pagination = null;
}

describe('React Adapter: Pagination', () => {
  if (!Pagination) {
    it.skip('Pagination adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Pagination',
    Component: Pagination,
    defaultProps: {}
  });
});
