/**
 * React adapter tests for Paint
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Paint: any;

try {
  const module = await import('../../../adapters/react/paint');
  Paint = module.Paint;
} catch (error) {
  console.warn('React adapter for paint not built yet. Run: npm run build:react');
  Paint = null;
}

describe('React Adapter: Paint', () => {
  if (!Paint) {
    it.skip('Paint adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Paint',
    Component: Paint,
    defaultProps: {}
  });
});
