/**
 * React adapter tests for PdfViewer
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let PdfViewer: any;

try {
  const module = await import('../../../adapters/react/pdf-viewer');
  PdfViewer = module.PdfViewer;
} catch (error) {
  console.warn('React adapter for pdf-viewer not built yet. Run: npm run build:react');
  PdfViewer = null;
}

describe('React Adapter: PdfViewer', () => {
  if (!PdfViewer) {
    it.skip('PdfViewer adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'PdfViewer',
    Component: PdfViewer,
    defaultProps: {}
  });
});
