/**
 * React adapter tests for PermissionMatrix
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let PermissionMatrix: any;

try {
  const module = await import('../../../adapters/react/permission-matrix');
  PermissionMatrix = module.PermissionMatrix;
} catch (error) {
  console.warn('React adapter for permission-matrix not built yet. Run: npm run build:react');
  PermissionMatrix = null;
}

describe('React Adapter: PermissionMatrix', () => {
  if (!PermissionMatrix) {
    it.skip('PermissionMatrix adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'PermissionMatrix',
    Component: PermissionMatrix,
    defaultProps: {}
  });
});
