/**
 * React adapter tests for PodcastPlayer
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let PodcastPlayer: any;

try {
  const module = await import('../../../adapters/react/podcast-player');
  PodcastPlayer = module.PodcastPlayer;
} catch (error) {
  console.warn('React adapter for podcast-player not built yet. Run: npm run build:react');
  PodcastPlayer = null;
}

describe('React Adapter: PodcastPlayer', () => {
  if (!PodcastPlayer) {
    it.skip('PodcastPlayer adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'PodcastPlayer',
    Component: PodcastPlayer,
    defaultProps: {}
  });
});
