/**
 * React adapter tests for Popover
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Popover: any;

try {
  const module = await import('../../../adapters/react/popover');
  Popover = module.Popover;
} catch (error) {
  console.warn('React adapter for popover not built yet. Run: npm run build:react');
  Popover = null;
}

describe('React Adapter: Popover', () => {
  if (!Popover) {
    it.skip('Popover adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Popover',
    Component: Popover,
    defaultProps: {}
  });
});
