/**
 * React adapter tests for PricingTable
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let PricingTable: any;

try {
  const module = await import('../../../adapters/react/pricing-table');
  PricingTable = module.PricingTable;
} catch (error) {
  console.warn('React adapter for pricing-table not built yet. Run: npm run build:react');
  PricingTable = null;
}

describe('React Adapter: PricingTable', () => {
  if (!PricingTable) {
    it.skip('PricingTable adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'PricingTable',
    Component: PricingTable,
    properties: [
      { name: 'variant', value: 'test' },
      { name: 'annual', value: 'test' }
    ],
    events: [
      { name: 'onPlanSelect' }
    ],
    defaultProps: {}
  });
});
