/**
 * React adapter tests for ProductCard
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let ProductCard: any;

try {
  const module = await import('../../../adapters/react/product-card');
  ProductCard = module.ProductCard;
} catch (error) {
  console.warn('React adapter for product-card not built yet. Run: npm run build:react');
  ProductCard = null;
}

describe('React Adapter: ProductCard', () => {
  if (!ProductCard) {
    it.skip('ProductCard adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'ProductCard',
    Component: ProductCard,
    defaultProps: {}
  });
});
