/**
 * React adapter tests for Progress
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Progress: any;

try {
  const module = await import('../../../adapters/react/progress');
  Progress = module.Progress;
} catch (error) {
  console.warn('React adapter for progress not built yet. Run: npm run build:react');
  Progress = null;
}

describe('React Adapter: Progress', () => {
  if (!Progress) {
    it.skip('Progress adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Progress',
    Component: Progress,
    properties: [
      { name: 'value', value: 'test' },
      { name: 'max', value: 10 },
      { name: 'indeterminate', value: 'test' }
    ],
    variants: ["linear","circular"],
    sizes: ["small","medium","large"],
    defaultProps: {}
  });
});
