/**
 * React adapter tests for ProgressRing
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let ProgressRing: any;

try {
  const module = await import('../../../adapters/react/progress-ring');
  ProgressRing = module.ProgressRing;
} catch (error) {
  console.warn('React adapter for progress-ring not built yet. Run: npm run build:react');
  ProgressRing = null;
}

describe('React Adapter: ProgressRing', () => {
  if (!ProgressRing) {
    it.skip('ProgressRing adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'ProgressRing',
    Component: ProgressRing,
    defaultProps: {}
  });
});
