/**
 * React adapter tests for QrReader
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let QrReader: any;

try {
  const module = await import('../../../adapters/react/qr-reader');
  QrReader = module.QrReader;
} catch (error) {
  console.warn('React adapter for qr-reader not built yet. Run: npm run build:react');
  QrReader = null;
}

describe('React Adapter: QrReader', () => {
  if (!QrReader) {
    it.skip('QrReader adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'QrReader',
    Component: QrReader,
    defaultProps: {}
  });
});
