/**
 * React adapter tests for Radio
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Radio: any;

try {
  const module = await import('../../../adapters/react/radio');
  Radio = module.Radio;
} catch (error) {
  console.warn('React adapter for radio not built yet. Run: npm run build:react');
  Radio = null;
}

describe('React Adapter: Radio', () => {
  if (!Radio) {
    it.skip('Radio adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Radio',
    Component: Radio,
    properties: [
      { name: 'checked', value: 'test' }
    ],
    events: [
      { name: 'onChange' }
    ],
    sizes: ["small","medium","large"],
    isForm: true,
    formOptions: {
      valueType: 'string',
      defaultValue: 'test'
    },
    defaultProps: {}
  });
});
