/**
 * React adapter tests for RangeSlider
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let RangeSlider: any;

try {
  const module = await import('../../../adapters/react/range-slider');
  RangeSlider = module.RangeSlider;
} catch (error) {
  console.warn('React adapter for range-slider not built yet. Run: npm run build:react');
  RangeSlider = null;
}

describe('React Adapter: RangeSlider', () => {
  if (!RangeSlider) {
    it.skip('RangeSlider adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'RangeSlider',
    Component: RangeSlider,
    defaultProps: {}
  });
});
