/**
 * React adapter tests for Rating
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Rating: any;

try {
  const module = await import('../../../adapters/react/rating');
  Rating = module.Rating;
} catch (error) {
  console.warn('React adapter for rating not built yet. Run: npm run build:react');
  Rating = null;
}

describe('React Adapter: Rating', () => {
  if (!Rating) {
    it.skip('Rating adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Rating',
    Component: Rating,
    defaultProps: {}
  });
});
