/**
 * React adapter tests for Receipt
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Receipt: any;

try {
  const module = await import('../../../adapters/react/receipt');
  Receipt = module.Receipt;
} catch (error) {
  console.warn('React adapter for receipt not built yet. Run: npm run build:react');
  Receipt = null;
}

describe('React Adapter: Receipt', () => {
  if (!Receipt) {
    it.skip('Receipt adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Receipt',
    Component: Receipt,
    defaultProps: {}
  });
});
