/**
 * React adapter tests for Recipe
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Recipe: any;

try {
  const module = await import('../../../adapters/react/recipe');
  Recipe = module.Recipe;
} catch (error) {
  console.warn('React adapter for recipe not built yet. Run: npm run build:react');
  Recipe = null;
}

describe('React Adapter: Recipe', () => {
  if (!Recipe) {
    it.skip('Recipe adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Recipe',
    Component: Recipe,
    defaultProps: {}
  });
});
