/**
 * React adapter tests for Sankey
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Sankey: any;

try {
  const module = await import('../../../adapters/react/sankey');
  Sankey = module.Sankey;
} catch (error) {
  console.warn('React adapter for sankey not built yet. Run: npm run build:react');
  Sankey = null;
}

describe('React Adapter: Sankey', () => {
  if (!Sankey) {
    it.skip('Sankey adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Sankey',
    Component: Sankey,
    properties: [
      { name: 'nodeWidth', value: 'test' },
      { name: 'nodePadding', value: 'test' },
      { name: 'alignment', value: 'test' },
      { name: 'showLabels', value: 'test' },
      { name: 'showValues', value: 'test' },
      { name: 'animation', value: 'test' }
    ],
    events: [
      { name: 'onSankeyNodeClick' },
      { name: 'onSankeyLinkClick' },
      { name: 'onSankeyHover' }
    ],
    defaultProps: {}
  });
});
