/**
 * React adapter tests for Scheduler
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Scheduler: any;

try {
  const module = await import('../../../adapters/react/scheduler');
  Scheduler = module.Scheduler;
} catch (error) {
  console.warn('React adapter for scheduler not built yet. Run: npm run build:react');
  Scheduler = null;
}

describe('React Adapter: Scheduler', () => {
  if (!Scheduler) {
    it.skip('Scheduler adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Scheduler',
    Component: Scheduler,
    properties: [
      { name: 'resources', value: [{ id: '1', name: 'Room A' }] },
      { name: 'events', value: [{ id: '1', title: 'Meeting', start: '09:00', end: '10:00' }] },
      { name: 'view', value: 'week' },
      { name: 'date', value: '2024-01-15' },
      { name: 'granularity', value: 30 },
      { name: 'startHour', value: 8 },
      { name: 'endHour', value: 18 }
    ],
    events: [],
    defaultProps: {}
  });
});
