/**
 * React adapter tests for SegmentedControl
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let SegmentedControl: any;

try {
  const module = await import('../../../adapters/react/segmented-control');
  SegmentedControl = module.SegmentedControl;
} catch (error) {
  console.warn('React adapter for segmented-control not built yet. Run: npm run build:react');
  SegmentedControl = null;
}

describe('React Adapter: SegmentedControl', () => {
  if (!SegmentedControl) {
    it.skip('SegmentedControl adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'SegmentedControl',
    Component: SegmentedControl,
    defaultProps: {}
  });
});
