/**
 * React adapter tests for Select
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Select: any;

try {
  const module = await import('../../../adapters/react/select');
  Select = module.Select;
} catch (error) {
  console.warn('React adapter for select not built yet. Run: npm run build:react');
  Select = null;
}

describe('React Adapter: Select', () => {
  if (!Select) {
    it.skip('Select adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Select',
    Component: Select,
    properties: [
      { name: 'placeholder', value: 'Test placeholder' },
      { name: 'multiple', value: 'test' }
    ],
    events: [
      { name: 'onChange' }
    ],
    variants: ["outlined","filled","underlined"],
    sizes: ["small","medium","large"],
    isForm: true,
    formOptions: {
      valueType: 'string',
      defaultValue: 'test'
    },
    defaultProps: {}
  });
});
