/**
 * React adapter tests for Signature
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Signature: any;

try {
  const module = await import('../../../adapters/react/signature');
  Signature = module.Signature;
} catch (error) {
  console.warn('React adapter for signature not built yet. Run: npm run build:react');
  Signature = null;
}

describe('React Adapter: Signature', () => {
  if (!Signature) {
    it.skip('Signature adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Signature',
    Component: Signature,
    defaultProps: {}
  });
});
