/**
 * React adapter tests for Skeleton
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Skeleton: any;

try {
  const module = await import('../../../adapters/react/skeleton');
  Skeleton = module.Skeleton;
} catch (error) {
  console.warn('React adapter for skeleton not built yet. Run: npm run build:react');
  Skeleton = null;
}

describe('React Adapter: Skeleton', () => {
  if (!Skeleton) {
    it.skip('Skeleton adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Skeleton',
    Component: Skeleton,
    defaultProps: {}
  });
});
