/**
 * React adapter tests for Slider
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Slider: any;

try {
  const module = await import('../../../adapters/react/slider');
  Slider = module.Slider;
} catch (error) {
  console.warn('React adapter for slider not built yet. Run: npm run build:react');
  Slider = null;
}

describe('React Adapter: Slider', () => {
  if (!Slider) {
    it.skip('Slider adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Slider',
    Component: Slider,
    properties: [
      { name: 'min', value: 10 },
      { name: 'max', value: 10 },
      { name: 'step', value: 10 }
    ],
    events: [
      { name: 'onChange' },
      { name: 'onInput' }
    ],
    sizes: ["small","medium","large"],
    isForm: true,
    formOptions: {
      valueType: 'number',
      defaultValue: 0
    },
    defaultProps: {}
  });
});
