/**
 * React adapter tests for Sortable
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Sortable: any;

try {
  const module = await import('../../../adapters/react/sortable');
  Sortable = module.Sortable;
} catch (error) {
  console.warn('React adapter for sortable not built yet. Run: npm run build:react');
  Sortable = null;
}

describe('React Adapter: Sortable', () => {
  if (!Sortable) {
    it.skip('Sortable adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Sortable',
    Component: Sortable,
    defaultProps: {}
  });
});
