/**
 * React adapter tests for Sparkline
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Sparkline: any;

try {
  const module = await import('../../../adapters/react/sparkline');
  Sparkline = module.Sparkline;
} catch (error) {
  console.warn('React adapter for sparkline not built yet. Run: npm run build:react');
  Sparkline = null;
}

describe('React Adapter: Sparkline', () => {
  if (!Sparkline) {
    it.skip('Sparkline adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Sparkline',
    Component: Sparkline,
    defaultProps: {}
  });
});
