/**
 * React adapter tests for Spinner
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Spinner: any;

try {
  const module = await import('../../../adapters/react/spinner');
  Spinner = module.Spinner;
} catch (error) {
  console.warn('React adapter for spinner not built yet. Run: npm run build:react');
  Spinner = null;
}

describe('React Adapter: Spinner', () => {
  if (!Spinner) {
    it.skip('Spinner adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Spinner',
    Component: Spinner,
    sizes: ["small","medium","large"],
    defaultProps: {}
  });
});
