/**
 * React adapter tests for SplitButton
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let SplitButton: any;

try {
  const module = await import('../../../adapters/react/split-button');
  SplitButton = module.SplitButton;
} catch (error) {
  console.warn('React adapter for split-button not built yet. Run: npm run build:react');
  SplitButton = null;
}

describe('React Adapter: SplitButton', () => {
  if (!SplitButton) {
    it.skip('SplitButton adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'SplitButton',
    Component: SplitButton,
    defaultProps: {}
  });
});
