/**
 * React adapter tests for SplitPane
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let SplitPane: any;

try {
  const module = await import('../../../adapters/react/split-pane');
  SplitPane = module.SplitPane;
} catch (error) {
  console.warn('React adapter for split-pane not built yet. Run: npm run build:react');
  SplitPane = null;
}

describe('React Adapter: SplitPane', () => {
  if (!SplitPane) {
    it.skip('SplitPane adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'SplitPane',
    Component: SplitPane,
    defaultProps: {}
  });
});
