/**
 * React adapter tests for Spotlight
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe, it, expect, vi } from 'vitest';
import { testComponent, testComponentProperties, testComponentEvents } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Spotlight: any;

try {
  const module = await import('../../../adapters/react/spotlight');
  Spotlight = module.Spotlight;
} catch (error) {
  console.warn('React adapter for spotlight not built yet. Run: npm run build:react');
  Spotlight = null;
}

describe('React Adapter: Spotlight', () => {
  if (!Spotlight) {
    it.skip('Spotlight adapter not built', () => {});
    return;
  }

  describe('Basic Component Tests', () => {
    testComponent({
      name: 'Spotlight',
      Component: Spotlight,
      defaultProps: {}
    });
  });

  describe('Properties', () => {
    testComponentProperties('Spotlight', Spotlight, [
      { name: 'steps', value: [{ target: '#step1', content: 'First step' }], type: 'object' },
      { name: 'currentIndex', value: 0, type: 'number' },
      { name: 'currentIndex', value: 1, type: 'number' },
      { name: 'active', value: true, type: 'boolean' },
      { name: 'active', value: false, type: 'boolean' }
    ]);

    it('should accept steps array property', () => {
      const steps = [
        { target: '#button', content: 'Click this button' },
        { target: '#input', content: 'Enter text here' }
      ];
      const element = React.createElement(Spotlight, { steps });
      expect(element).toBeDefined();
      expect(element.props.steps).toBe(steps);
    });

    it('should accept currentIndex property', () => {
      const element = React.createElement(Spotlight, { currentIndex: 2 });
      expect(element.props.currentIndex).toBe(2);
    });

    it('should accept active boolean property', () => {
      const element = React.createElement(Spotlight, { active: true });
      expect(element.props.active).toBe(true);
    });

    it('should accept inactive state', () => {
      const element = React.createElement(Spotlight, { active: false });
      expect(element.props.active).toBe(false);
    });
  });

  describe('Combined Props', () => {
    it('should handle all properties together', () => {
      const steps = [
        { target: '#step1', title: 'Welcome', content: 'Get started' },
        { target: '#step2', title: 'Next', content: 'Continue' }
      ];
      
      const element = React.createElement(Spotlight, {
        steps,
        currentIndex: 0,
        active: true
      });
      
      expect(element).toBeDefined();
      expect(element.props.steps).toBe(steps);
      expect(element.props.currentIndex).toBe(0);
      expect(element.props.active).toBe(true);
    });
  });
});

// Need to import React for the test-helpers functions
import React from 'react';
