/**
 * React adapter tests for Spotlight
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Spotlight: any;

try {
  const module = await import('../../../adapters/react/spotlight');
  Spotlight = module.Spotlight;
} catch (error) {
  console.warn('React adapter for spotlight not built yet. Run: npm run build:react');
  Spotlight = null;
}

describe('React Adapter: Spotlight', () => {
  if (!Spotlight) {
    it.skip('Spotlight adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Spotlight',
    Component: Spotlight,
    defaultProps: {}
  });
});
