/**
 * React adapter tests for StatGroup
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let StatGroup: any;

try {
  const module = await import('../../../adapters/react/stat-group');
  StatGroup = module.StatGroup;
} catch (error) {
  console.warn('React adapter for stat-group not built yet. Run: npm run build:react');
  StatGroup = null;
}

describe('React Adapter: StatGroup', () => {
  if (!StatGroup) {
    it.skip('StatGroup adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'StatGroup',
    Component: StatGroup,
    defaultProps: {}
  });
});
