/**
 * React adapter tests for StepInput
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let StepInput: any;

try {
  const module = await import('../../../adapters/react/step-input');
  StepInput = module.StepInput;
} catch (error) {
  console.warn('React adapter for step-input not built yet. Run: npm run build:react');
  StepInput = null;
}

describe('React Adapter: StepInput', () => {
  if (!StepInput) {
    it.skip('StepInput adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'StepInput',
    Component: StepInput,
    defaultProps: {}
  });
});
