/**
 * React adapter tests for Stepper
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Stepper: any;

try {
  const module = await import('../../../adapters/react/stepper');
  Stepper = module.Stepper;
} catch (error) {
  console.warn('React adapter for stepper not built yet. Run: npm run build:react');
  Stepper = null;
}

describe('React Adapter: Stepper', () => {
  if (!Stepper) {
    it.skip('Stepper adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Stepper',
    Component: Stepper,
    defaultProps: {}
  });
});
