/**
 * React adapter tests for Switch
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Switch: any;

try {
  const module = await import('../../../adapters/react/switch');
  Switch = module.Switch;
} catch (error) {
  console.warn('React adapter for switch not built yet. Run: npm run build:react');
  Switch = null;
}

describe('React Adapter: Switch', () => {
  if (!Switch) {
    it.skip('Switch adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Switch',
    Component: Switch,
    properties: [
      { name: 'checked', value: 'test' }
    ],
    events: [
      { name: 'onChange' }
    ],
    sizes: ["small","medium","large"],
    isForm: true,
    formOptions: {
      valueType: 'boolean',
      defaultValue: false
    },
    defaultProps: {}
  });
});
