/**
 * React adapter tests for Table
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Table: any;

try {
  const module = await import('../../../adapters/react/table');
  Table = module.Table;
} catch (error) {
  console.warn('React adapter for table not built yet. Run: npm run build:react');
  Table = null;
}

describe('React Adapter: Table', () => {
  if (!Table) {
    it.skip('Table adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Table',
    Component: Table,
    defaultProps: {}
  });
});
