/**
 * React adapter tests for Tabs
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Tabs: any;

try {
  const module = await import('../../../adapters/react/tabs');
  Tabs = module.Tabs;
} catch (error) {
  console.warn('React adapter for tabs not built yet. Run: npm run build:react');
  Tabs = null;
}

describe('React Adapter: Tabs', () => {
  if (!Tabs) {
    it.skip('Tabs adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Tabs',
    Component: Tabs,
    defaultProps: {}
  });
});
