/**
 * React adapter tests for TagInput
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let TagInput: any;

try {
  const module = await import('../../../adapters/react/tag-input');
  TagInput = module.TagInput;
} catch (error) {
  console.warn('React adapter for tag-input not built yet. Run: npm run build:react');
  TagInput = null;
}

describe('React Adapter: TagInput', () => {
  if (!TagInput) {
    it.skip('TagInput adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'TagInput',
    Component: TagInput,
    defaultProps: {}
  });
});
