/**
 * React adapter tests for Tag
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Tag: any;

try {
  const module = await import('../../../adapters/react/tag');
  Tag = module.Tag;
} catch (error) {
  console.warn('React adapter for tag not built yet. Run: npm run build:react');
  Tag = null;
}

describe('React Adapter: Tag', () => {
  if (!Tag) {
    it.skip('Tag adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Tag',
    Component: Tag,
    defaultProps: {}
  });
});
