/**
 * React adapter tests for Testimonial
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Testimonial: any;

try {
  const module = await import('../../../adapters/react/testimonial');
  Testimonial = module.Testimonial;
} catch (error) {
  console.warn('React adapter for testimonial not built yet. Run: npm run build:react');
  Testimonial = null;
}

describe('React Adapter: Testimonial', () => {
  if (!Testimonial) {
    it.skip('Testimonial adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Testimonial',
    Component: Testimonial,
    defaultProps: {}
  });
});
