/**
 * React adapter tests for Textarea
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Textarea: any;

try {
  const module = await import('../../../adapters/react/textarea');
  Textarea = module.Textarea;
} catch (error) {
  console.warn('React adapter for textarea not built yet. Run: npm run build:react');
  Textarea = null;
}

describe('React Adapter: Textarea', () => {
  if (!Textarea) {
    it.skip('Textarea adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Textarea',
    Component: Textarea,
    properties: [
      { name: 'placeholder', value: 'Test placeholder' },
      { name: 'rows', value: 5 },
      { name: 'maxlength', value: 100 },
      { name: 'readonly', value: true },
      { name: 'resize', value: 'vertical' }
    ],
    events: [
      { name: 'onInput' },
      { name: 'onChange' },
      { name: 'onFocus' },
      { name: 'onBlur' }
    ],
    variants: ["outlined","filled","underlined"],
    sizes: ["small","medium","large"],
    isForm: true,
    formOptions: {
      valueType: 'string',
      defaultValue: 'test'
    },
    defaultProps: {}
  });
});
