/**
 * React adapter tests for Timer
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Timer: any;

try {
  const module = await import('../../../adapters/react/timer');
  Timer = module.Timer;
} catch (error) {
  console.warn('React adapter for timer not built yet. Run: npm run build:react');
  Timer = null;
}

describe('React Adapter: Timer', () => {
  if (!Timer) {
    it.skip('Timer adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Timer',
    Component: Timer,
    defaultProps: {}
  });
});
