/**
 * React adapter tests for TimeRangePicker
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let TimeRangePicker: any;

try {
  const module = await import('../../../adapters/react/time-range-picker');
  TimeRangePicker = module.TimeRangePicker;
} catch (error) {
  console.warn('React adapter for time-range-picker not built yet. Run: npm run build:react');
  TimeRangePicker = null;
}

describe('React Adapter: TimeRangePicker', () => {
  if (!TimeRangePicker) {
    it.skip('TimeRangePicker adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'TimeRangePicker',
    Component: TimeRangePicker,
    properties: [
      { name: 'granularity', value: 'test' },
      { name: 'startTime', value: 'test' },
      { name: 'endTime', value: 'test' },
      { name: 'disabledRanges', value: 'test' },
      { name: 'format', value: 'test' },
      { name: 'multiple', value: 'test' },
      { name: 'readonly', value: true }
    ],
    events: [
      { name: 'onChange' },
      { name: 'onTimeRangeSelect' },
      { name: 'onTimeRangeComplete' }
    ],
    isForm: true,
    formOptions: {
      valueType: 'string',
      defaultValue: 'test'
    },
    defaultProps: {}
  });
});
