/**
 * React adapter tests for Timeline
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Timeline: any;

try {
  const module = await import('../../../adapters/react/timeline');
  Timeline = module.Timeline;
} catch (error) {
  console.warn('React adapter for timeline not built yet. Run: npm run build:react');
  Timeline = null;
}

describe('React Adapter: Timeline', () => {
  if (!Timeline) {
    it.skip('Timeline adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Timeline',
    Component: Timeline,
    defaultProps: {}
  });
});
