/**
 * React adapter tests for TimePicker
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let TimePicker: any;

try {
  const module = await import('../../../adapters/react/time-picker');
  TimePicker = module.TimePicker;
} catch (error) {
  console.warn('React adapter for time-picker not built yet. Run: npm run build:react');
  TimePicker = null;
}

describe('React Adapter: TimePicker', () => {
  if (!TimePicker) {
    it.skip('TimePicker adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'TimePicker',
    Component: TimePicker,
    defaultProps: {}
  });
});
