/**
 * React adapter tests for Toast
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Toast: any;

try {
  const module = await import('../../../adapters/react/toast');
  Toast = module.Toast;
} catch (error) {
  console.warn('React adapter for toast not built yet. Run: npm run build:react');
  Toast = null;
}

describe('React Adapter: Toast', () => {
  if (!Toast) {
    it.skip('Toast adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Toast',
    Component: Toast,
    defaultProps: {}
  });
});
