/**
 * React adapter tests for Tooltip
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Tooltip: any;

try {
  const module = await import('../../../adapters/react/tooltip');
  Tooltip = module.Tooltip;
} catch (error) {
  console.warn('React adapter for tooltip not built yet. Run: npm run build:react');
  Tooltip = null;
}

describe('React Adapter: Tooltip', () => {
  if (!Tooltip) {
    it.skip('Tooltip adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Tooltip',
    Component: Tooltip,
    properties: [
      { name: 'content', value: 'test' },
      { name: 'position', value: 'top' }
    ],
    defaultProps: {}
  });
});
