/**
 * React adapter tests for Tree
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Tree: any;

try {
  const module = await import('../../../adapters/react/tree');
  Tree = module.Tree;
} catch (error) {
  console.warn('React adapter for tree not built yet. Run: npm run build:react');
  Tree = null;
}

describe('React Adapter: Tree', () => {
  if (!Tree) {
    it.skip('Tree adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Tree',
    Component: Tree,
    defaultProps: {}
  });
});
