/**
 * React adapter tests for Treemap
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Treemap: any;

try {
  const module = await import('../../../adapters/react/treemap');
  Treemap = module.Treemap;
} catch (error) {
  console.warn('React adapter for treemap not built yet. Run: npm run build:react');
  Treemap = null;
}

describe('React Adapter: Treemap', () => {
  if (!Treemap) {
    it.skip('Treemap adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Treemap',
    Component: Treemap,
    properties: [
      { name: 'showLabels', value: 'test' },
      { name: 'showValues', value: 'test' },
      { name: 'colorScheme', value: 'test' },
      { name: 'padding', value: 'test' },
      { name: 'animation', value: 'test' }
    ],
    events: [
      { name: 'onTreemapClick' },
      { name: 'onTreemapHover' },
      { name: 'onTreemapDrill' }
    ],
    defaultProps: {}
  });
});
