/**
 * React adapter tests for UserCard
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let UserCard: any;

try {
  const module = await import('../../../adapters/react/user-card');
  UserCard = module.UserCard;
} catch (error) {
  console.warn('React adapter for user-card not built yet. Run: npm run build:react');
  UserCard = null;
}

describe('React Adapter: UserCard', () => {
  if (!UserCard) {
    it.skip('UserCard adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'UserCard',
    Component: UserCard,
    defaultProps: {}
  });
});
