/**
 * React adapter tests for VideoPlayer
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let VideoPlayer: any;

try {
  const module = await import('../../../adapters/react/video-player');
  VideoPlayer = module.VideoPlayer;
} catch (error) {
  console.warn('React adapter for video-player not built yet. Run: npm run build:react');
  VideoPlayer = null;
}

describe('React Adapter: VideoPlayer', () => {
  if (!VideoPlayer) {
    it.skip('VideoPlayer adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'VideoPlayer',
    Component: VideoPlayer,
    defaultProps: {}
  });
});
