/**
 * React adapter tests for VirtualScroller
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let VirtualScroller: any;

try {
  const module = await import('../../../adapters/react/virtual-scroller');
  VirtualScroller = module.VirtualScroller;
} catch (error) {
  console.warn('React adapter for virtual-scroller not built yet. Run: npm run build:react');
  VirtualScroller = null;
}

describe('React Adapter: VirtualScroller', () => {
  if (!VirtualScroller) {
    it.skip('VirtualScroller adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'VirtualScroller',
    Component: VirtualScroller,
    defaultProps: {}
  });
});
