/**
 * React adapter tests for Waterfall
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Waterfall: any;

try {
  const module = await import('../../../adapters/react/waterfall');
  Waterfall = module.Waterfall;
} catch (error) {
  console.warn('React adapter for waterfall not built yet. Run: npm run build:react');
  Waterfall = null;
}

describe('React Adapter: Waterfall', () => {
  if (!Waterfall) {
    it.skip('Waterfall adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Waterfall',
    Component: Waterfall,
    defaultProps: {}
  });
});
