/**
 * React adapter tests for Weather
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let Weather: any;

try {
  const module = await import('../../../adapters/react/weather');
  Weather = module.Weather;
} catch (error) {
  console.warn('React adapter for weather not built yet. Run: npm run build:react');
  Weather = null;
}

describe('React Adapter: Weather', () => {
  if (!Weather) {
    it.skip('Weather adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'Weather',
    Component: Weather,
    defaultProps: {}
  });
});
