/**
 * React adapter tests for WorkOrder
 * Auto-generated by scripts/generate-react-tests.js
 */

import { describe } from 'vitest';
import { testComponent } from '../test-helpers';

// Import the React adapter
// Note: Run 'npm run build:react' to generate adapters before testing
let WorkOrder: any;

try {
  const module = await import('../../../adapters/react/work-order');
  WorkOrder = module.WorkOrder;
} catch (error) {
  console.warn('React adapter for work-order not built yet. Run: npm run build:react');
  WorkOrder = null;
}

describe('React Adapter: WorkOrder', () => {
  if (!WorkOrder) {
    it.skip('WorkOrder adapter not built', () => {});
    return;
  }

  testComponent({
    name: 'WorkOrder',
    Component: WorkOrder,
    defaultProps: {}
  });
});
