/**
 * Focused tests for tooling/generators/generate-react-tests.js:
 * WIP exclusion via the shared .wip helper and deterministic stale-test removal.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs';
import os from 'os';
import path from 'path';
import {
  discoverTestComponents,
  generateTestFile,
  removeStaleGeneratedTests
} from '../../tooling/generators/generate-react-tests.js';
import { getWipComponents } from '../../tooling/shared/wip-components.js';

const GENERATED_MARKER = 'Auto-generated by tooling/generators/generate-react-tests.js';

describe('generate-react-tests: WIP exclusion', () => {
  it('excludes every .wip component from discovery', () => {
    const components = discoverTestComponents();
    for (const wip of getWipComponents()) {
      expect(components).not.toContain(wip);
    }
  });

  it('excludes spreadsheet while it is listed in .wip', () => {
    expect(getWipComponents().has('spreadsheet')).toBe(true);
    expect(discoverTestComponents()).not.toContain('spreadsheet');
  });

  it('discovers released components in sorted, deterministic order', () => {
    const components = discoverTestComponents();
    expect(components).toContain('button');
    expect(components).not.toContain('theme');
    expect(components).toEqual([...components].sort());
  });
});

describe('generate-react-tests: generated file content', () => {
  it('stamps the generated marker so stale removal can identify its own output', () => {
    const content = generateTestFile('button', { events: ['onClick'] });
    expect(content).toContain(GENERATED_MARKER);
    expect(content).toContain("adapters/react/button");
  });
});

describe('generate-react-tests: stale test removal', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'snice-gen-tests-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('removes generated tests for components no longer released', () => {
    fs.writeFileSync(path.join(tmpDir, 'spreadsheet.test.tsx'), generateTestFile('spreadsheet'));
    fs.writeFileSync(path.join(tmpDir, 'button.test.tsx'), generateTestFile('button'));

    const removed = removeStaleGeneratedTests(tmpDir, ['button']);

    expect(removed).toEqual(['spreadsheet.test.tsx']);
    expect(fs.existsSync(path.join(tmpDir, 'spreadsheet.test.tsx'))).toBe(false);
    expect(fs.existsSync(path.join(tmpDir, 'button.test.tsx'))).toBe(true);
  });

  it('never deletes hand-written tests lacking the generated marker', () => {
    const handWritten = path.join(tmpDir, 'spreadsheet.test.tsx');
    fs.writeFileSync(handWritten, "import { describe } from 'vitest';\n// hand-written\n");

    const removed = removeStaleGeneratedTests(tmpDir, ['button']);

    expect(removed).toEqual([]);
    expect(fs.existsSync(handWritten)).toBe(true);
  });

  it('removes stale tests carrying the legacy scripts/ marker but spares hand-written files', () => {
    const legacy = path.join(tmpDir, 'spreadsheet.test.tsx');
    fs.writeFileSync(legacy, '/**\n * Auto-generated by scripts/generate-react-tests.js\n */\n');
    const handWritten = path.join(tmpDir, 'custom.test.tsx');
    fs.writeFileSync(handWritten, "import { describe } from 'vitest';\n// hand-written\n");

    const removed = removeStaleGeneratedTests(tmpDir, ['button']);

    expect(removed).toEqual(['spreadsheet.test.tsx']);
    expect(fs.existsSync(legacy)).toBe(false);
    expect(fs.existsSync(handWritten)).toBe(true);
  });

  it('ignores non-test files and returns sorted results', () => {
    fs.writeFileSync(path.join(tmpDir, 'README.md'), GENERATED_MARKER);
    fs.writeFileSync(path.join(tmpDir, 'zeta.test.tsx'), generateTestFile('zeta'));
    fs.writeFileSync(path.join(tmpDir, 'alpha.test.tsx'), generateTestFile('alpha'));

    const removed = removeStaleGeneratedTests(tmpDir, []);

    expect(removed).toEqual(['alpha.test.tsx', 'zeta.test.tsx']);
    expect(fs.existsSync(path.join(tmpDir, 'README.md'))).toBe(true);
  });

  it('handles a missing tests directory without throwing', () => {
    expect(removeStaleGeneratedTests(path.join(tmpDir, 'nope'), ['button'])).toEqual([]);
  });
});
