/**
 * React Adapter Tests - Index
 *
 * This file imports all component test suites to ensure they run together.
 * Individual component tests are in the components/ directory.
 */

import { describe, it, expect } from 'vitest';

describe('React Adapters - All Components', () => {
  it('should have test helper utilities', async () => {
    const helpers = await import('./test-helpers');
    expect(helpers.testComponent).toBeDefined();
    expect(helpers.testComponentBasics).toBeDefined();
    expect(helpers.testComponentProperties).toBeDefined();
    expect(helpers.testComponentEvents).toBeDefined();
    expect(helpers.testFormComponent).toBeDefined();
    expect(helpers.testComponentVariants).toBeDefined();
    expect(helpers.testComponentSizes).toBeDefined();
  });

  it('should have React adapter infrastructure', async () => {
    const wrapper = await import('../../adapters/react/wrapper');
    expect(wrapper.createReactAdapter).toBeDefined();
    expect(wrapper.useSniceFormValue).toBeDefined();
  });

  it('should have type definitions', async () => {
    const types = await import('../../adapters/react/types');
    expect(types).toBeDefined();
  });

  it('should have utility functions', async () => {
    const utils = await import('../../adapters/react/utils');
    expect(utils.kebabToCamel).toBeDefined();
    expect(utils.camelToKebab).toBeDefined();
    expect(utils.extractComponentMetadata).toBeDefined();
    expect(utils.isFormAssociated).toBeDefined();
    expect(utils.waitForComponentDefinition).toBeDefined();
  });
});

// Import individual component tests
// These are auto-generated by scripts/generate-react-tests.js
// Run 'npm run generate:react-tests' to regenerate them

// Note: Individual test files are imported by the test runner automatically
// This file serves as an entry point and verification that the test infrastructure exists
